### ISSUE TITLE
prefill with default values: "Replacement for CBO real GDP growth"

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#128]
Currently the 'replacement for CBO real GDP growth' parameter on TaxBrain defaults to zero and is unselected. Could we prefill this with the default values for tax-calculator parameter that it links to, `_factor_target` in growth.json? 

(This is related to #127, since there are different values hardcoded for each year)

cc @talumbau 

@Amy-Xu, if this issue is resolved, do you think it would make sense to rename the long name in tax-calculator to "Real GDP growth rate" and then add to the description that it comes from CBO?

cc @jdebacker for relevancy to the annual growth param in og-usa

**Comment by Amy-Xu** [comment]
That sounds better than the current long name. Maybe something like 'Real GDP growth rate assumption'? or 'projection'? 

I thought the description already has where this parameter's from.

**Comment by talumbau** [comment]
looks like an abandoned issue that should be fixed. I'll take it.

**Comment by hdoupe** [comment]
I'm not sure if #128 was ever resolved. I don't think there is currently any type of growth specification in PolicyBrain. If this is the case, can we close this issue?

**Comment by MattHJensen** [comment]
We removed the relevant parameters. Closing.
