### ISSUE TITLE
What message should the user see when TaxBrain can't process the user input?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/PolicyBrain#234]
It seems likely that there could be legitimate user input that we don't currently validate properly on TaxBrain (see, e.g. #232). There could be text that a user enters that we will never properly validate, something like:

```
asdfasdf, *, 4500
```

but there might also be legitimate text that I can't think of a test for right now that could fail. Instead of just giving the user the "500 Internal Server Error", we could display an error message of some kind. The question is: what should this error message say? In the case of the above (which would obviously just be some kind of input mistake), we could display a message like:

Sorry, the text entry "asdfasdf, *, 4500" is not a valid entry for parameter XXX

Is that a good message? Is there a better choice? cc @MattHJensen @martinholmer

**Comment by martinholmer** [comment]
@talumbau said:
> we could display a message like:
>
> Sorry, the text entry "asdfasdf, *, 4500" is not a valid entry for parameter XXX
>
> Is that a good message? Is there a better choice?

I think any error message that indicates the invalid taxt entry and the parameter name is just fine.

**Comment by martinholmer** [comment]
@talumbau,  When do you plan on adding this (issue #234) error-reporting capability in TaxBrain?

**Comment by martinholmer** [comment]
Martin said about trapping the "500 Internal Server Error":
> I think any error message that indicates the invalid text-box entry and the parameter name is just fine.

and then asked:
> When do you plan on adding this (issue #234) error-reporting capability in TaxBrain?

This would be a major benefit in my selenium-based testing of TaxBrain.

At the moment, I know there are problems using the `*` notation for delayed reform implementation with the following parameters:
```
_ID_Casualty_frt
_ID_Charity_frt
_ID_Medical_frt
_ID_Miscellaneous_frt
```
And there are more problematic parameters because when I drop the above four parameters from a composite reform, I still get a "500 Internal Server Error" message.

@talumbau

**Comment by talumbau** [comment]
I have an idea on a reasonable kind of error message. It won't be perfect but it will be a good start. Can you point me to the selenium test that is failing for you? I had success in using your setup previously and this might help me debug.

**Comment by talumbau** [comment]
Oh, I will try to add the error handling today

**Comment by martinholmer** [comment]
T.J. (@talumbau) asked:
> Can you point me to the selenium test that is failing for you?

The all-together delayed reform is specified in [all-16-delay.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxbrain/all-16-delay.json) while the one-at-a-time delayed reforms are specified in [sep-16-delay.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxbrain/sep-16-delay.json).  In the `sep-16-delay.json` file, reforms using the following parameters are the first four to fail:
```
_ID_Casualty_frt
_ID_Charity_frt
_ID_Medical_frt
_ID_Miscellaneous_frt
```

**Comment by hdoupe** [comment]
This has been resolved.  See:
![screen shot 2017-11-28 at 10 40 00 am](https://user-images.githubusercontent.com/9206065/33328641-868b6656-d428-11e7-9346-2afeac5d07c9.png)
