### ISSUE TITLE
Add endpoint that submits microsim based on previous simulation number

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/PolicyBrain#301]
When running a "quick calculation", the user will get taken to a results page (quickly!) that will give them a quick estimate of the full results. On this results page, There will be text like this:

> "This calculation used only 2% of the available data and only calculated revenues for one year instead of ten. For the full results, click here"

The link available at "click here" will need to be a POST to start a new simulation. Rather than put all of the user's reform in this POST link, it seems reasonable to have the POST contain a key/value pair like:

```
    sim_result: <integer>
```

The web app will have a view that accepts this POST, and then kicks off a full microsim job with the same parameters that were used for the "quick calc" with the given simulation number.

**Comment by hdoupe** [comment]
Resolved via #299
