### ISSUE TITLE
Known issues with "Quick Calculation"

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/PolicyBrain#306]
- [ ]  The button does not appear when one chose to the "Edit Parameters" page
- [x] The indexing scheme for how we choose which worker nodes to select for a job is adversely impacted by Quick Calculations. Essentially, the indexing scheme is set up to increment by "NUM_BUDGET_YEARS" but the counting gets off because Quick Calculations are only for one year. The end result is that regular microsim jobs will have their performance adversely impacted.  This will have to be fixed.

**Comment by talumbau** [comment]
Re-opening until item 1 from above is resolved as well.

**Comment by martinholmer** [comment]
@talumbau,  As part of this pull request, can you change DataFrame.sample() random_state to 80 unless the one being used now produces sub-sample results that are even closer to full-sample results than a relative difference of 0.006 (that is, 0.6 percent) as described in [Tax-Calculator pull request #869](https://github.com/open-source-economics/Tax-Calculator/pull/869)?

@MattHJensen

**Comment by martinholmer** [comment]
@MattHJensen,  What is the status of TaxBrain "Quick Calculation" issue #306?
Is it safe to recommend in the user documentation the Quick Calculator option?

**Comment by MattHJensen** [comment]
> What is the status of TaxBrain "Quick Calculation" issue #306?

The quick calculation button is not available on TaxBrain presets, but it is available and working fine from the default input page.  

> Is it safe to recommend in the user documentation the Quick Calculator option?

Yes, although it would be helpful to add the caveat that it is not available for preset reforms, as some of users may work off of presets.

**Comment by martinholmer** [comment]
@MattHJensen said:
> @martinholmer The quick calculation button is not available on TaxBrain presets, but it is available and working fine from the default input page.
>
>> Is it safe to recommend in the user documentation the Quick Calculator option?
>
> Yes, although it would be helpful to add the caveat that it is not available for preset reforms, as some of users may work off of presets.

Yes, I guess it would be helpful in the short run, but since the goal is to make it eventually work for preset reforms, I think I'll leave that transitory detail out of the user documentation.

**Comment by MattHJensen** [comment]
> I think I'll leave that transitory detail out of the user documentation.

Ok, that makes a lot of sense to plan w/ the maintenance burden in mind.

**Comment by martinholmer** [comment]
As of August 2, 2017, the first bug item mentioned nearly a year ago in webapp-public issue #306 is still not fixed.  During the year since #306 was opened, the contents of the `puf.csv` file used by TaxBrain have changed somewhat, causing a sensible Quick-Calculation subsample to be 5% (not 2%) as described in webapp-public enhancement request #574.

Where do these two remaining TaxBrain Quick-Calculation bug-fixes stand in our priorities?

@brittainhard @PeterDSteinberg @hdoupe @GoFroggyRun
