### ISSUE TITLE
All open-source-economics packages should be built with conda-forge

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/PolicyBrain#320]
Conda-forge is a community driven Github organization for building conda packages. If we transition Tax-Calculator, OG-USA, and B-Tax to this build mechanism, it will significantly simplify the release process for the web application. Here is the link the conda forge:

https://conda-forge.github.io/

@PeterDSteinberg can you investigate this and see the LOE required here?

cc @MattHJensen

**Comment by MattHJensen** [comment]
@PeterDSteinberg, @jbcrail: should this issue remain open?

**Comment by hdoupe** [comment]
@MattHJensen I think we can close this. I don't see any upside to adding our packages to conda-forge when we have our own channel, OSPC.
