### ISSUE TITLE
Add visualizations to CCC

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#364]
It would be cool to generate visual outputs for CCC. We could start with a static version of the bubble plot. Assuming that the first step is a util in B-Tax, I opened https://github.com/open-source-economics/B-Tax/issues/106. 

![image](https://cloud.githubusercontent.com/assets/8301092/19401483/92ac0ac2-9229-11e6-9d21-dc962d998b25.png)

I'm not sure how these should fit into the output page. One option would be to include these above the table on the current output page. This seems fine for one or two, but might be a problem if we add several. We could start there and see how we like it, or others might have better ideas. 

cc @jdebacker @brendancol @talumbau

**Comment by jdebacker** [comment]
@MattHJensen , I'm a bit fan of doing this.  We could have a bubble plot as above by asset and one by industry above each of the respective tables.  I think this gives a much better way to visualize the differences, which I think have hard to get across with the deltas tables.

**Comment by MattHJensen** [comment]
> We could have a bubble plot as above by asset and one by industry above each of the respective tables. 

That'd be great.

**Comment by brendancol** [comment]
@MattHJensen @jdebacker sound good to me. Is this something to prioritize for the first release?

**Comment by MattHJensen** [comment]
All of the "next-release" tags are priority items, but this would be good if there are none of those on your plate.

**Comment by jdebacker** [comment]
How about we adapt the bubble graph that we did for the depreciation phaseout, but to represent the output currently in tables (e.g. depending on the radio button selected, it'll we have a y axis that is asset or industry categories, a horizontal axis that is the metr/metttr/cc/z values, and bubble sizes determined by asset values.  Bubble value will also vary if reform/baseline/difference is presented.

So we can pull off the sliders, but might have to do some work to adapt to industry names on the y-axis and be sure the horizontal axis can rescale to take into account reforms.

Glad to talk about this.  And I may be able to go a long way towards generating plots with each B-Tax run, but have no ideas how that would get sucked into CCC and displayed on the web.

cc @brendancol @MattHJensen

**Comment by MattHJensen** [comment]
> How about we adapt the bubble graph that we did for the depreciation phaseout, but to represent the output currently in tables (e.g. depending on the radio button selected, it'll we have a y axis that is asset or industry categories, a horizontal axis that is the metr/metttr/cc/z values, and bubble sizes determined by asset values. Bubble value will also vary if reform/baseline/difference is presented.

That makes sense to me. Later we can add the box and whisker plot. 

>  And I may be able to go a long way towards generating plots with each B-Tax run, but have no ideas how that would get sucked into CCC and displayed on the web.

Yes, I agree that it would make sense for the plotting capability to be a util in B-Tax (open-source-economics/B-Tax#106). That would parallel the style that we adopted for Tax-Calculator when @GoFroggyRun and @martinholmer added a new MTR plot capability to taxcalc/utils. It would be best of course if generating the plots and tables don't require separate runs, though.

**Comment by MattHJensen** [comment]
Should be doable to include the box and whisker plot now given https://github.com/open-source-economics/plots/pull/52.

**Comment by hdoupe** [comment]
PR #642 adds a plot for CCC. Do we want to keep this issue open or close and open up separate issues for future plots?

cc @jdebacker @MattHJensen

**Comment by jdebacker** [comment]
@hdoupe I think close this one.

**Comment by hdoupe** [comment]
Ok, thanks @jdebacker

**Comment by hdoupe** [comment]
Closed #364
