### ISSUE TITLE
Add start year value

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/PolicyBrain#399]
B-Tax [PR #107](https://github.com/open-source-economics/B-Tax/pull/107) will allow a flexible start year to update the business tax parameters to reflect values for years 2015-2020 (not yet merged to wait for feedback on what needs to be done for this to work with CCC).  We should allow a the user to define the year one is looking at in CCC.  This would be especially important for integration with Tax-Calculator.

**Comment by brittainhard** [comment]
@MattHJensen @talumbau so we need a dropdown to select the year, like in the Tax Calculator, but it needs to allow for years up to 2020?

**Comment by MattHJensen** [comment]
@brittainhard asked:

> so we need a dropdown to select the year, like in the Tax Calculator, but it needs to allow for years up to 2020? 

That sounds right. @jdebacker should be able to confirm.

**Comment by jdebacker** [comment]
That's right.  Acceptable values are 2015 to 2020.

cc @MattHJensen @brittainhard

**Comment by jdebacker** [comment]
@brittainhard We might want to address this soon as it appears that the default base year for the CCC web app maybe 2015 (see this [line](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/btax/helpers.py#L70) - whereas the default year for B-Tax is 2017.  

Also, for the user of CCC, the text indicate the baseline year is 2017 (though it is easy to miss this bit of text).

**Comment by hdoupe** [comment]
Closed via #849
