### ISSUE TITLE
add email option to wait screen

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/PolicyBrain#402]
A user should be able to add his/her email address from the wait screen while waiting for a TaxBrain job to finish. The user would get an email with the link to the job that is currently running.

**Comment by talumbau** [comment]
@MattHJensen here is the email wait screen issue. Which milestone do you think it should go in?

**Comment by MattHJensen** [comment]
Thanks @talumbau. Placing in b4 for now.

**Comment by hdoupe** [comment]
I think we should close this issue. The wait times for B-Tax and TaxBrain are under 5 minutes. That isn't too long to wait. Plus, they can record the run number from the url and re-visit the page at a later time.

**Comment by hdoupe** [comment]
Closed #402
