### ISSUE TITLE
Render Gallery Plots well to Mobile Devices

### ISSUE THREAD

**Issue by brendancol** [OpenSourcePolicyCenter/PolicyBrain#418]
- [ ] make adjustments to gallery page to make sure plot title properly displays on mobile devices
- [ ] see if simple adjustments can be made to @GoFroggyRun plot to make it render better on mobile devices
- [ ] test other plots and adjust accordingly

**Note:** A major part of the gallery-page's mission is to provide live versions of plots as a previews for users considering embedding.  Anything done to a plot in the gallery, must also be done when embedding on remote sites.  This means there is more onus on individual plot developers to create content which renders nicely on different platforms.

**Comment by hdoupe** [comment]
This feels like a very low priority issue right now. This can be re-opened in the future if a developer is interested in implementing this.

**Comment by hdoupe** [comment]
Closed #418
