### ISSUE TITLE
B-Tax running progress indicator

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#463]
When submitting a B-Tax model from `/ccc` , one is redirected to a progress bar page while the results are being calculated.  There currently is a bug where the progress bar shows gradual progress up to 100% as expected, but then drops back to 0% progress for 30 seconds or so before rendering okay results.  The following screenshots show what I'm talking about:

<img width="1088" alt="screen shot 2017-01-30 at 1 31 16 pm" src="https://cloud.githubusercontent.com/assets/1445602/22442717/21b8c36a-e6f1-11e6-944a-5df461853088.png">

<img width="1018" alt="screen shot 2017-01-30 at 1 32 41 pm" src="https://cloud.githubusercontent.com/assets/1445602/22442726/28ec485a-e6f1-11e6-948a-4381e54a9c56.png">

<img width="935" alt="screen shot 2017-01-30 at 1 32 44 pm" src="https://cloud.githubusercontent.com/assets/1445602/22442732/2d73740c-e6f1-11e6-8ce4-3daececafaf9.png">

*How to replicate:* `python manage.py runserver` with the environment variable BTAX_WORKERS set to `hostname:5050` where `hostname` is any of the IP addresses @brittainhard and I deployed last week in the test dropq workers cluster.

**Comment by jdebacker** [comment]
@PeterDSteinberg Is this still an issue?  I'm not noticing it now.

But in testing this, I see that perhaps we need to open an issue over in B-Tax about speeding up the calculations.  e.g. if no economic parameters are changed, then we could cut run time about in half by using cached baseline results.

**Comment by hdoupe** [comment]
I just ran a CCC reform and the progress bar worked as expected.

**Comment by hdoupe** [comment]
Closed #463
