### ISSUE TITLE
Misc. Credit Limits and Misc. Adjustment Haircuts not working

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#523]
There are a bunch of new parameters being added to the TB testing release. I found that, however, most, if not all, of those parameters are not working properly: input any valid reform would result in an error.

See TB error messages:

<img width="746" alt="screen shot 2017-04-04 at 9 32 21 pm" src="https://cloud.githubusercontent.com/assets/13324931/24707778/e713a872-19e2-11e7-8810-75a801bf94e1.png">

and 

<img width="722" alt="screen shot 2017-04-04 at 9 36 50 pm" src="https://cloud.githubusercontent.com/assets/13324931/24707780/e828d9ee-19e2-11e7-9765-4da20a5f08a3.png">

Those parameters are under the section Misc. Adjustment Haircuts of Above The Line Deduction and Misc. Credit Limits of Nonrefundable Credits.

cc @brittainhard @MattHJensen

**Comment by MattHJensen** [comment]
Replicated. Here's an example: http://ospc-taxes7.herokuapp.com/taxbrain/1238/

**Comment by brittainhard** [comment]
@MattHJensen @GoFroggyRun Looks like the error is coming from here: https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L329 , most likely on the node and not the test app.

**Comment by MattHJensen** [comment]
@brittainhard, I talked to Sean and he confirms that everything is working fine locally. Could the nodes still be on 0.7.9?

**Comment by brittainhard** [comment]
@MattHJensen it's possible. I'll ssh in and take a look.
