### ISSUE TITLE
Add Ability to Disable Fields

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#531]
This would allow us to hide fields from `current_law_polcy.json` of  `taxcalc` that we don't users to have access to yet.

It would be a good idea to remove all of the old form generation logic, from when the form inputs where hard-coded.

**Comment by hdoupe** [comment]
Closing #531. PolicyBrain should be as close to taxcalc as possible. There is no need to shield PolicyBrain users from features that python programmers can access via the taxcalc package.

**Comment by hdoupe** [comment]
Closed #531
