### ISSUE TITLE
Link to Dynamic Simulations should work from /file w no behavioral assumptions

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#535]
Here is an example of a /file reform with no behavioral assumptions, only reform parameters. 

https://www.ospc.org/taxbrain/11037/

However, the link to dynamic simulations is blocked anyways:

![image](https://cloud.githubusercontent.com/assets/8301092/25043581/f5a4dbbe-20ee-11e7-80b3-664cbb43500a.png)

**Comment by brittainhard** [comment]
@MattHJensen , looking at https://github.com/OpenSourcePolicyCenter/webapp-public/issues/535, it looks like a feature. There is code in deploy and in webapp that makes sure no simulation can be run off of file-based reforms. This was changed to solve https://github.com/OpenSourcePolicyCenter/webapp-public/issues/431. Do we want to walk back these changes and allow simulations on file-based reforms?

**Comment by MattHJensen** [comment]
We do not want to allow dynamic simulations for file based reforms where an assumptions file is present. We should allow dynamic simulations for file based reforms where no assumption file is present.

**Comment by hdoupe** [comment]
Closed via #669
