### ISSUE TITLE
Update documentation based on findings with Sean today

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#547]
Regarding the deploy and webapp-public docs:

 * Be sure to mention postgres complexity better
 * More docs on labels main vs dev
 * Show how to use a localhost:5050 worker
 * Make webapp guess localhost if needed

**Comment by MattHJensen** [comment]
@PeterDSteinberg, @GoFroggyRun, is this resolved? Should it have an assignee?

**Comment by hdoupe** [comment]
Nothing ever became of this issue. Closing.

**Comment by hdoupe** [comment]
Closed #547
