### ISSUE TITLE
Consider "cluster-ssh" tool for redeploy.py

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#570]
Running redeploy.py on several nodes takes several terminals.  It's not too much work to cut and paste one command to each terminal, but it would be easier to have `cluster-ssh` automate so it could be run in one terminal with a list of IP addresses.

**Comment by hdoupe** [comment]
This is a great idea. However, it would be better addressed in a comprehensive deployment issue.

**Comment by hdoupe** [comment]
Closed #570
