### ISSUE TITLE
remove newsletter signup

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#575]
I also just added a drip.co signup to ospc.org. This means we should: 

- [ ]  eliminate our pre-existing signup capabilities
- [ ] send all emails in our current database to edward.brown@aei.org for inclusion in the drip.co database.

**Comment by hdoupe** [comment]
@MattHJensen where do we stand on #575 -- "remove newsletter signup"?

**Comment by MattHJensen** [comment]
I am going to close this for now. I am not entirely satisfied with drip.co, so we may as well leave both for now.
