### ISSUE TITLE
Ensure creation of new backend nodes can control versions installed

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#576]
We recently merged #556 that moved what was formerly the `deploy` repo to the `./deploy` folder in this webapp-public repo.  One remaining issue is to follow up on new node creation with that `./deploy` folder, ensuring that versions can be controlled for Tax-Calculator, B-Tax, and OG-USA, either from conda installs (with any anaconda.org user/label) or `setup.py` installs.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, is this still required now that we are pinning versions?

**Comment by hdoupe** [comment]
This is resolved. We do not have any issues specifying package versions to the worker nodes.

**Comment by hdoupe** [comment]
Closed #576
