### ISSUE TITLE
Ensure heroku can control versions installed on push events

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#577]
We need to make several changes to ensure that `heroku push` events are configurable with respect to the Tax-Calculator, B-Tax, and OG-USA versions that are installed, either from conda or setup.py install.

**Comment by hdoupe** [comment]
We do not currently have any issues with pushing specific versions of OSPC models to heroku. The deployment approach should be cleaned up and streamlined to resolve the confusion introduced by the many environment config files.

**Comment by hdoupe** [comment]
Closed #577
