### ISSUE TITLE
Webapp Cleanup 

### ISSUE THREAD

**Issue by ecbrown5** [OpenSourcePolicyCenter/PolicyBrain#584]
The "About" page on ospc.org needs to include Cost of Capital Calculator with logo under "Our Products."

Also on the "About" page, all three of the social media links (Twitter, Facebook,LinkedIn) are inactive.

The "Apps" link on the bottom of the home page is also inactive.

Thank you for your help!

**Comment by MattHJensen** [comment]
@GoFroggyRun, could you add this to your list of issues to handle when you are back in the U.S.?
