### ISSUE TITLE
flatblocks -> something checked into repo

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#588]
After I updated the ospc.org/taxbrain user tips in response to #585, @martinholmer asked:

> @MattHJensen, So how did this new documentation get added to TaxBrain?
> I can't see any pull request that made the change. 

What happened is that I updated a [django-flatbock](https://pypi.python.org/pypi/django-flatblocks) via the Django admin. 

@martinholmer further noted that: 

>  If we want TaxBrain development to be more transparent, changes like this need to be more visible.

I agree entirely. Our current reliance on flatblocks has a few detrimental effects

- undermines the open approach of the TaxBrain project. 
- means that we are not tracking changes to text and not reaping the benefits of version control. 
- means that our test app often looks different than our production app. 

One simple solution that comes to mind would be to edit the html directly in the webapp-public source code rather than via flatbocks. That would be fine with me, although other suggestions are very welcome. 

@brittainhard @GoFroggyRun @hdoupe @martinholmer

**Comment by hdoupe** [comment]
@MattHJensen said

> One simple solution that comes to mind would be to edit the html directly in the webapp-public source code rather than via flatbocks. 

This makes sense to me.  I don't know what the technical obstacles are here, but the current system discourages contributors from making what should be trivial fixes (see #649, #662).  

@martinholmer

**Comment by hdoupe** [comment]
Closed via #711
