### ISSUE TITLE
Submitting with no upload file causes 500 error

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#589]
Need to add some logic to ensure file exists.

**Comment by martinholmer** [comment]
Using TaxBrain 1.0.1 on 2017-08-16, this bug persists.

Going to the file-upload page and immediately clicking on the `Show me the results!' button, produces this:

![screen shot 2017-08-16 at 6 51 02 pm](https://user-images.githubusercontent.com/12170745/29388721-4b07dc10-82b4-11e7-8d6c-c1866c2b3b86.png)

**Comment by hdoupe** [comment]
Closed via #641 
<img width="821" alt="screen shot 2017-09-28 at 5 01 19 pm" src="https://user-images.githubusercontent.com/9206065/30990392-00a538de-a46f-11e7-9457-87c0884bd563.png">

**Comment by martinholmer** [comment]
Issue fixed in TaxBrain 1.0.3.  @hdoupe, thanks for the work on this.
