### ISSUE TITLE
Fix Deployment Tests

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#601]
Deployment tests were not properly migrated, and therefore fail when `py.test` is run with no path specified.

**Comment by MattHJensen** [comment]
@brittainhard, is this resolved?

**Comment by brittainhard** [comment]
@MattHJensen not yet, but I can roll this issue into some broader deployment updating and testing that i'm currently doing.

**Comment by MattHJensen** [comment]
Ok. Thanks @brittainhard

**Comment by hdoupe** [comment]
This spring we will revamp the deployment process. I'm going to close this in favor of a comprehensive issue describing the new deployment approach and the testing that will be required there.

**Comment by hdoupe** [comment]
Closed #601
