### ISSUE TITLE
Documenting TaxBrain/Tax-Calculator Interactions

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#604]
**High-level documentation of how TaxBrain (TB) works as an interface to Tax-Calculator (TC)**

*This initial comment will eventually contain the high-level documentation for static tax analysis.
I will edit it as people answer questions posed in subsequent comments.*

At the highest level of abstraction, TB contains three components:

- **TB INPUT GUI**  This component creates the policy-parameter input form in a browser and sends the user-specified input to TC for calculation.

- **TB FILE UPLOAD** This component creates the reform-file and assumption-file upload form and sends the user-specified forms to TC for calculation.

- **TB RESULTS GUI** This component creates the TC-results-viewing forms in a browser and allows users to download the tax-calculation results in several formats.

The relationship between these three TB components and TC can be visualized as follows:
```
----------------               ------------------
| TB INPUT GUI |               | TB FILE UPLOAD |
----------------               ------------------
          |                         |
          |                         |
          |          ------         | 
          ---------> | TC |<---------
                     ------
                       |
                       |
------------------     |
| TB RESULTS GUI |<-----
------------------
```

**TB INPUT GUI DOCUMENTATION**

- **Form-Creation Code Location**
   ... info goes here ...

- **Input-Sending Code Location**
   ... info goes here ...

- **Kind of Input Sent**
   ... info goes here ...

**TB FILE UPLOAD DOCUMENTATION**

- **Form-Creation Code Location**
   ... info goes here ...

- **Input-Sending Code Location**
   ... info goes here ...

- **Kind of Input Sent**
   JSON reform file and JSON assumption file.

**TB RESULTS GUI DOCUMENTATION**

- **Kind of Results Received**
   ... info goes here ...

- **Results-Receiving Code Location**
   ... info goes here ...

- **Form-Creation Code Location**
   ... info goes here ...

- **Results-Download Code Location**
   ... info goes here ...

@talumbau @PeterDSteinberg @brittainhard 
@MattHJensen @hdoupe @GoFroggyRun

**Comment by martinholmer** [comment]
First question about issue #604 is whether this high-level view of TB/TC interactions is correct.

Second set of questions is where is the code corresponding to these components.  In which webapp-public directories?  In which files? In which functions?

Even if you know (or think you know) answers to only a part of the whole picture, please contribute your knowledge by adding a comment to issue #604.

@talumbau @PeterDSteinberg @brittainhard
@MattHJensen @hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
TB INPUT GUI DOCUMENTATION

- Form-Creation Code Location
        The format of the TaxBrain input page is set in [`templates/taxbrain/input_form.html`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/templates/taxbrain/input_form.html).
        

- Input-Sending Code Location
       The input from the submitted form is received by [`webapp/apps/taxbrain/views.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/views.py).  The function [`personal_results`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/views.py#L328) receives the input data and cleans and validates it in the [`PersonalExemptionsForm`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/forms.py#L80) class in [`taxbrain/forms.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/forms.py).  The data is sent to the function [`views.process_model`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/views.py#L133) which submits the data to the function [`DropqCompute.submit_dropq_calculation`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py#L61) in [`compute.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py).

-    Kind of Input Sent
          The input is received as a `requests` object where `request.Request` is a dictionary containing reform parameters, the start year, and a boolean variable indicating whether to do a full calculation or not.  This data is cleaned and validated and then sent to the function [`DropqCompute.submit_dropq_calculation`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py#L61) in [`taxbrain/compute.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py).  The variables sent are `start_year` and `worker_data` which is a Python dictionary containing the cleaned reform parameters.

TB FILE UPLOAD DOCUMENTATION

- Form-Creation Code Location
    The format of the TaxBrain input page is set in [`templates/taxbrain/input_file.html`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/templates/taxbrain/input_file.html).

- Input-Sending Code Location
       The input is received in [`webapp/apps/taxbrain/views.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/views.py) by the function [`file_input`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/views.py#L201).

- Kind of Input Sent
The input is received as a `requests` object where `request.Request` is a dictionary and `request.Request['start_year']` is the first budget year of the reform.  `request.File` is a dictionary where `request.File['docfile']` is the uploaded json reform file and `request.File['assumpfile']` is the uploaded json assumption file if one was uploaded.  These files are formatted into a `taxcalc.Policy` dictionary using the function `taxcalc.Calculator.read_json_param_files`.  The resulting dictionaries are sent to the function [`DropqCompute.submit_dropq_calculation`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py#L61) in [`compute.py`](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/compute.py).


@martinholmer This is my understanding of how the data is received and formatted.  I hope this helps with the documentation.

**Comment by martinholmer** [comment]
@hdoupe,  Thanks so much for your contribution to TaxBrain issue #604.
This information will be very helpful going forward.
