### ISSUE TITLE
Revenue table (Print, etc.) buttons disappear when selecting different (Reform, etc.) table

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#613]
@GoFroggyRun after looking at this issue, it looks like the buttons for the table aren't being re-rendered when a different table is looked at. Unfortunately, the buttons are added after the table has already been rendered. 

The buttons are added here: 
https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/static/js/taxbrain-tablebuilder.js#L554-L567

But then need to be added again here after re-rendering: 
https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/static/js/taxbrain-tablebuilder.js#L261-L272

So, the fiscal table is being re-rendered but it's getting rid of the buttons each time it's being re-rendered. Hope that makes sense.

I spent a couple hours looking at it and couldn't make headway. I can take another look tomorrow.

**Comment by GoFroggyRun** [comment]
@brittainhard Thanks for looking into the issue, and pointing out related code lines. Your explanation makes a lot sense to me. I'll try to play with those code at the same time to see if I can get any progress or not.

**Comment by martinholmer** [comment]
This is still a **major** problem in TaxBrain 1.0.3.
@GoFroggyRun, can you fix this problem?

@MattHJensen @hdoupe @brittainhard

**Comment by GoFroggyRun** [comment]
@martinholmer Thanks for looking into this issue. 

@brittainhard and I have been working on this issue. Neither of us, however, was able to fix it. 
I'll take another look sometime this week to see if I can get any headway.

**Comment by GoFroggyRun** [comment]
I have been working on this issue for a couple more days, and was able to have "something" showing up when these tables are re-rendered. However, it fails when I tried to replace "something" with the tool box. 

My approach was to play with the [re-render function](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/static/js/taxbrain-tablebuilder.js#L251-L263) that tries to build tool boxes after the table being re-rendered. Not too sure why it still doesn't work though. 

@brittainhard do you have any input on this?

**Comment by brittainhard** [comment]
@GoFroggyRun have you got some code written for this that I could take a look at?

**Comment by GoFroggyRun** [comment]
@brittainhard I opened #705, which includes the code change as well as its effect.

**Comment by GoFroggyRun** [comment]
@brittainhard do you have any output on this? If possible, we could do some pair programming. 

cc @atxsder @MattHJensen
