### ISSUE TITLE
1.0.2 Release

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#624]
@hdoupe @martinholmer @MattHJensen @GoFroggyRun  I've made a milestone for the 1.0.2 release. Can we discuss what fixes and PRs we want in that milestone? I know for sure I want #612 and #589 fixed. Any other suggestions?

**Comment by hdoupe** [comment]
@brittainhard what do you think about tackling #619?  I would like to fix #596, #598, and #607 as soon as possible since they will lead to incorrect results.  It appears that solving #619 will take care of #596, #598, and #607.  That way we don't have to fix the latter three bugs twice.

I'm interested in working on this if you're busy working on other stuff before the next release.

cc @martinholmer @MattHJensen @GoFroggyRun

**Comment by hdoupe** [comment]
#622 should be ready to go.  This points the TaxBrain urls to the correct version of the relevant package instead of the master repo on github.  It also removes the reference to the commit ID.

**Comment by hdoupe** [comment]
@brittainhard I have some tests that post reforms to TaxBrain using the requests library and compare the results with those generated by sending the reform data straight to taxcalc.  Should we try to include those in this release?

cc @martinholmer @MattHJensen @GoFroggyRun

**Comment by brittainhard** [comment]
@hdoupe #619 looks like a good fix, and I think i'm the only person that can tackle it. I'll take a look.

In regards to the test PRs, those are always important to have. It would be good if you could associate that code with an issue, and add that issue to the milestone.

**Comment by brittainhard** [comment]
With #622, I think its better to add issues to these milestones and not PRs. Can you open an issue for that PR?

**Comment by GoFroggyRun** [comment]
@brittainhard, #611, #621 and #623 should be ready to go as well. It would be great to include them in 1.0.2 release.

**Comment by brittainhard** [comment]
@GoFroggyRun great, can you add the associated issues to the milestone?

**Comment by GoFroggyRun** [comment]
@brittainhard it seems that I wasn't able to associate those issues to the milestone, but related issues are #584 and #545.

**Comment by brittainhard** [comment]
I added them.

**Comment by brittainhard** [comment]
@GoFroggyRun did you have time to take another look at #613 ?

**Comment by hdoupe** [comment]
@brittainhard I just opened an issue #625 for PR #622.

**Comment by hdoupe** [comment]
@brittainhard said
> @hdoupe #619 looks like a good fix, and I think i'm the only person that can tackle it. I'll take a look.

Ok sounds good.  Let me know if there is anything I can do to help.

**Comment by GoFroggyRun** [comment]
@brittainhard I did look at it and worked on it for a while, I was not able to, however, arrive at an easy fix. We might have to include that in the next release.

**Comment by GoFroggyRun** [comment]
@brittainhard it would also be helpful to include #626 in the milestone that resolves #620.

**Comment by martinholmer** [comment]
@brittainhard said in webapp-public issue #624 wrt TaxBrain release 1.0.2:
> #619 looks like a good fix, and I think i'm the only person that can tackle it. I'll take a look.

Being able to implement the TaxBrain changes described in #619 requires Tax-Calculator changes that are not in 0.9.2, but will be included in Tax-Calculator 0.9.3.  Would it facilitate your work on #619 if we created 0.9.3 now (or in the next few days)?  Please advise.

@MattHJensen @hdoupe @GoFroggyRun

**Comment by MattHJensen** [comment]
@brittainhard, what's the status of #619? If you aren't already deep into it, I think it makes sense for @hdoupe to do some exploratory work and then pull you in if he runs into trouble.

**Comment by brittainhard** [comment]
@MattHJensen I was going to start work on it today, but id be willing to focus on other things and just give him some guidance.

**Comment by MattHJensen** [comment]
@brittainhard said: "but id be willing to focus on other things and just give him some guidance." 

Let's give that a try. I think it will be a good learning experience for @hdoupe. Will also be great for you to have more bandwidth to dedicate to reviewing open PRs.

**Comment by brittainhard** [comment]
Prelease is now up.
