### ISSUE TITLE
Fix Issue with non-capitalized Names

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/PolicyBrain#633]
This was supposed to have been fixed in a previous taxcalc release, but the problem is persisting. @MattHJensen are you okay with fixing this on the TaxBrain side?

**Comment by martinholmer** [comment]
@brittainhard said in #633:
> This was supposed to have been fixed in a previous taxcalc release, but the problem is persisting.

What do you mean by that?  What exactly is wrong and didn't get fixed in Tax-Calculator?

@MattHJensen

**Comment by brittainhard** [comment]
The inputs in the taxbrain form look like this:

![screen shot 2017-08-22 at 11 46 13 am](https://user-images.githubusercontent.com/5440553/29577035-9a943fb0-872f-11e7-917e-a014bbc1e854.png)

All those names need to be capitalized. I had code that would capitalize all these names, but @MattHJensen wanted it removed, since the names for the inputs coming from TaxCalc were going to be capitalized.

Took a second look, and it does look like `current_law_policy.json` params do have capitalized names. I'll take a look at the code and see why this isn't bubbling up.

**Comment by martinholmer** [comment]
@brittainhard said:
> All those names need to be capitalized. 

But don't forget all the acronymns in the "box" names that TaxBrain is incorrectly switching to lower-case.  The most prominent of which, is TaxBrain's use of "fica" instead of "FICA".

@MattHJensen
