### ISSUE TITLE
Fiscal Table Enhancement

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#643]
Per request from @brittainhard, this issue summarizes one remaining enhancement from issue #545, item 2.

As pointed out by @martinholmer in #545:

>A key statistic is missing from the Total Liabilities tables: the ten-year totals. Most users will want the ten-year total for each row in the Total Liabilities table, but it is not there at the end of the row where most users would expect to see it. Can we add a ten-year total column on the far right? 

In brief, a column needs to be added to the current fiscal year table, on the far right. The column should sum up all previous numerical results in the row. For example, in the screenshot below, the added column would have a value of 0.9 for the first row, individual income tax liability change.

<img width="1131" alt="screen shot 2017-08-31 at 3 07 02 pm" src="https://user-images.githubusercontent.com/13324931/29940714-158dfbea-8e5e-11e7-8829-df6812cdb2c5.png">
 
I have been working on this for a while, mainly concerned with JavaScript, or more precisely the [taxbrain-tablebuilder.js](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/static/js/taxbrain-tablebuilder.js#L193-L245) file. However, I wasn't able to find an elegant approach to patch this enhancement. 

@brittainhard Could you take a look and advice please?

**Comment by brittainhard** [comment]
@GoFroggyRun looking at this now.

**Comment by brittainhard** [comment]
@GoFroggyRun looking at the data, it seems like you can insert a "summary" column into the table on the Django side and then have the frontend render it. Currently working along that line, i'll let you know how it goes.

**Comment by GoFroggyRun** [comment]
Close via #646. Thanks @brittainhard.
