### ISSUE TITLE
Itemized Deduction switches all off on edit parameters page

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#659]
After the user submits a calculation and goes back to edit parameters, all itemized deduction switches are set to off.  However, there are not any issues with passing the switch parameters to `taxcalc` for the initial calculation.

**Comment by hdoupe** [comment]
@GoFroggyRun do you have any ideas here?  In [`taxbrain/views.edit_personal_results`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views.py#L610), a new form is created from the data submitted in the previous simulation.  The itemized deduction switches have the correct value.  I know this by checking after submitting the following reform:

![screen shot 2017-09-20 at 2 16 57 pm](https://user-images.githubusercontent.com/9206065/30660446-cdb76b6a-9e0e-11e7-926d-274652f690b1.png)


```
    try:
        url = OutputUrl.objects.get(pk=pk)
    except:
        raise Http404

    model = TaxSaveInputs.objects.get(pk=url.model_pk)
    start_year = model.first_year
    print ('edit', dict(model.__dict__))
    form_personal_exemp = PersonalExemptionForm(first_year=start_year, instance=model)
    taxbrain_data = dict(dict(form_personal_exemp.__dict__)['instance'].__dict__)
    del taxbrain_data['tax_result']
    print('form edit', [(key, taxbrain_data[key]) for key in taxbrain_data if key.startswith('ID_Benefit')])
```

prints:

```[('ID_BenefitSurtax_trt', u''), ('ID_BenefitSurtax_crt', u''), ('ID_BenefitSurtax_Switch_0', u'1.0'), ('ID_BenefitSurtax_Switch_3', u'1.0'), ('ID_BenefitSurtax_Switch_2', u'0.0'), ('ID_BenefitSurtax_Switch_5', u'1.0'), ('ID_BenefitSurtax_Switch_4', u'0.0'), ('ID_BenefitSurtax_Switch_6', u'1.0'), ('ID_BenefitCap_rt', u''), ('ID_BenefitSurtax_em_3', u''), ('ID_BenefitSurtax_em_4', u''), ('ID_BenefitSurtax_em_2', u''), ('ID_BenefitSurtax_em_0', u''), ('ID_BenefitSurtax_em_1', u''), ('ID_BenefitCap_Switch_3', u'0.0'), ('ID_BenefitCap_Switch_2', u'1.0'), ('ID_BenefitCap_Switch_1', u'1.0'), ('ID_BenefitCap_Switch_0', u'0.0'), ('ID_BenefitCap_Switch_6', u'0.0'), ('ID_BenefitCap_Switch_5', u'1.0'), ('ID_BenefitCap_Switch_4', u'1.0'), ('ID_BenefitSurtax_Switch_1', u'1.0')```

which is what we expect.

Sometime between this and sending the context to the input form here:
```
    init_context = {
        'form': form_personal_exemp,#PersonalExemptionForm(first_year=start_year),#form_personal_exemp,
        'params': nested_form_parameters(int(start_year)),
        'taxcalc_version': taxcalc_vers_disp,
        'webapp_version': webapp_vers_disp,
        'start_years': START_YEARS,
        'start_year': str(start_year),
        'is_edit_page': True
    }
    return render(request, 'taxbrain/input_form.html', init_context)
```

The itemized deduction switches are all turned off.  Any ideas would be greatly appreciated.

**Comment by GoFroggyRun** [comment]
@hdoupe are you working on local right now? 

I tried the following, and the editing page looks fine to me: 

[#11543 Result Page](https://www.ospc.org/taxbrain/11543/) 
[#11543 Edit Page](https://www.ospc.org/taxbrain/edit/11543/)

and 

[#16930 Result Page](https://www.ospc.org/taxbrain/16930/)
[#16930 Edit Page](https://www.ospc.org/taxbrain/edit/16930/)

**Comment by hdoupe** [comment]
@GoFroggyRun Yes, I'm on local working with [this fork](https://github.com/hdoupe/PolicyBrain/tree/submit_quickcalc_bugfix) version 1.0.2.

**Comment by GoFroggyRun** [comment]
@hdoupe I tired without updating to 1.0.2. And the switches are working just fine on my local. 

Now trying with 1.0.2.

**Comment by hdoupe** [comment]
Ok, cool thanks.

**Comment by GoFroggyRun** [comment]
@hdoupe I can now confirm this issue. It seems that all switches are working just fine before 1.0.2 release. So it reasonable to believe this must has something to do with one of those PRs toward 1.0.2?

**Comment by hdoupe** [comment]
@GoFroggyRun said
> So it reasonable to believe this must has something to do with one of those PRs toward 1.0.2?

Yes, this is the case.  All parameters except for the itemized deduction switches appear correctly on the edit parameters page.  Per my [comment](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/659#issuecomment-330938104) here, the data is saved in the form but perhaps the switch values are not saved in the correct place.
