### ISSUE TITLE
No reform information shown on the result page

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#661]
For some reason, detailed reform information is not shown when users are submitting reforms via JSON file. See the result [here](https://www.ospc.org/taxbrain/11532/).

**Comment by hdoupe** [comment]
@GoFroggyRun this should be resolved.  Check out #658

**Comment by GoFroggyRun** [comment]
@hdoupe I see. Thanks! 
Closing. Already resolved via #658.
