### ISSUE TITLE
Documentation for PolicyBrain needs update

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#663]
The current [instructions](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/README.md) for PolicyBrain are outdated, especially the local development part. I'll work on revising it.

**Comment by hdoupe** [comment]
Thanks @GoFroggyRun

**Comment by brittainhard** [comment]
Yeah that's badly out of date. Thanks @GoFroggyRun

**Comment by hdoupe** [comment]
Closed via #702
