### ISSUE TITLE
Why this TaxBrain code?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#667]
In the `taxbrain/views.py` file, there is this code:
```
def read_json_reform(reform, assumptions, map_back_to_tb={}):
    """
    Read reform and parse errors

    returns reform and assumption dictionaries that are compatible with
            taxcalc.Policy.implement_reform
            parsed warning and error messsages to be displayed on input page
            if necessary
    """
    policy_dict = taxcalc.Calculator.read_json_param_files(
        reform,
        assumptions,
        arrays_not_lists=False
    )
    # get errors and warnings on parameters that do not cause ValueErrors
    errors_warnings = taxcalc.dropq.reform_warnings_errors(policy_dict)
    errors_warnings = parse_errors_warnings(errors_warnings,
                                            map_back_to_tb)
    # separate reform and assumptions
    reform_dict = policy_dict["policy"]
    assumptions_dict = {k: v for k, v in policy_dict.items() if k != "policy"}

    return reform_dict, assumptions_dict, errors_warnings
```
My question is why is `arrays_not_lists=False` used in the call to taxcalc.Calculator.read_json_reform_files?

**Comment by martinholmer** [comment]
@hdoupe,  Do you know the answer to my question in PB issue #667?

**Comment by hdoupe** [comment]
I think the logic is that we want Python lists returned instead of numpy arrays.  This way the policy dictionary is JSON serializable.

**Comment by martinholmer** [comment]
@hdoupe said:
> I think the logic is that we want Python lists returned instead of numpy arrays. This way the policy dictionary is JSON serializable.

OK.  Can you remind me why TaxBrain needs to convert policy dictionary back into JSON?
The input to the `read_json_parameter_objects()`method is already JSON.  So, don't you already have the JSON representation of the reform file contents?

**Comment by hdoupe** [comment]
@martinholmer  When we submit the user data to the model, we calculate each year separately.  To do so, we send the data to several other AWS EC2 machines which requires the data to be converted back to JSON after it is read by the `read_json_parameter_objects()` method.

At least this is my understanding of what is happening.  @brittainhard can you confirm that this is what is happening?

**Comment by martinholmer** [comment]
@hdoupe said:
> When we submit the user data to the model, we calculate each year separately. To do so, we send the data to several other AWS EC2 machines which requires the data to be converted back to JSON after it is read by the `read_json_parameter_objects()` method.

OK, that makes sense.  It is the need to do distributed processing that is the reason.
Thanks for the tutorial.
