### ISSUE TITLE
Fix mislabeled "Macro Elasticities Simulation" button

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#673]
On the [Choose a Dynamic Simulation Type](http://www.ospc.org/dynamic/17527/?start_year=2017) page, there is a button labeled "Macro Elasticities Simulation".  But when you click on that button and go to the [macro page](http://www.ospc.org/dynamic/macro/17527/?start_year=2017), there is only one elasticity to specify.

So, to reduce the chance of user confusion about where the other elasticities are, it seems as if the button should be labeled "Macro Elasticity Simulation".

Also, the title of the [macro page](http://www.ospc.org/dynamic/macro/17527/?start_year=2017) should be changed from "Macroeconomic Elasticities" to "Macroeconomic Elasticity Simulation" and the text, which was copied and pasted from the docstring in the `taxcalc/macro_elasticity.py` file, needs to reflect the corrections and revisions made in [Tax-Calculator pull request 1572](https://github.com/open-source-economics/Tax-Calculator/pull/1572).

And finally, the title on the one-line table is confusing.  Here is what it looks like now:

![screen shot 2017-10-05 at 6 49 30 am](https://user-images.githubusercontent.com/12170745/31223922-da800dc0-a999-11e7-83cb-94d3f7da1170.png)

The label to the far left of the line of results is fine.  The title should be changed to read something like:
`Percentage Change in GDP`.

@MattHJensen @feenberg @hdoupe @GoFroggyRun

**Comment by MattHJensen** [comment]
+1
