### ISSUE TITLE
Eliminating year selection button for "Macro Elasticities Simulation"

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#683]
The result page for Macro Elasticities Simulation includes a selection button on the top that allows users to choose from different year value, as shown below:

<img width="986" alt="screen shot 2017-10-04 at 7 06 23 pm" src="https://user-images.githubusercontent.com/13324931/31203923-416f7f4c-a937-11e7-896f-9b0754c51388.png">

The selection button, however, doesn't actually change anything. We should eliminate the button to avoid confusion.

**Comment by martinholmer** [comment]
@GoFroggyRun, good problem finding in TaxBrain issue #683.
You suggested solution (removing the dropdown year menu) makes sense to me.

@MattHJensen @hdoupe

**Comment by martinholmer** [comment]
@GoFroggyRun, when you do the work you suggested in issue #683 be sure to also
do the edits scheduled in issue #673.

@MattHJensen @hdoupe

**Comment by GoFroggyRun** [comment]
Closed via #684
