### ISSUE TITLE
TaxBrain 1.0.3 bug-warning wrong

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#685]
Many improvements in 1.0.3.  Thanks to all who worked on the newest version.
But there is one glaring error as seen in the following screen shot.

![screen shot 2017-10-05 at 3 36 53 pm](https://user-images.githubusercontent.com/12170745/31248935-870cf7da-a9e3-11e7-9e12-7c7a36b224ad.png)

My understanding is that TaxBrain 1.0.3 had fixed the personal refundable credit bug by switching to the approach advocated by @talumbau in issue #619.  Am I wrong about that?

If my understanding is correct, shouldn't this warning be removed?

@MattHJensen @hdoupe @GoFroggyRun @brittainhard

**Comment by MattHJensen** [comment]
@martinholmer, could you retitle this with a more informative issue name? I will handle the bug.

**Comment by MattHJensen** [comment]
@martinholmer, thanks again for pointing this out. It is resolved now. 

I hope that these changes can be made transparently soon.

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for the quick resolution of #685.
