### ISSUE TITLE
CCC hanging while calculations are running

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#686]
CCC is not generating results for me. I decreased the top business tax rate to .3. 

http://www.ospc.org/ccc/880/

cc @hdoupe

**Comment by hdoupe** [comment]
Thanks for opening an issue.  @brittainhard and I are trying to fix it now.

**Comment by hdoupe** [comment]
The test app was running Bokeh version 0.12.7 but the production app was pinned to Bokeh 0.12.5.  This was an issue that we had in the test app deployment.  This should be resolve by PR #687

**Comment by MattHJensen** [comment]
Do you think it would make sense to add a test to #687 to try to catch this type of test in the future or alternatively to open a new issue for adding such a test?

**Comment by martinholmer** [comment]
@hdoupe said:
> The test app was running Bokeh version 0.12.7 but the production app was pinned to Bokeh 0.12.5. This was an issue that we had in the test app deployment. This should be resolve by PR #687.

But if you just moved it (rather than put it in both files) won't the test app not work?
I guess another way of expression my confused ignorance is by asking this question:
What is the role of the `deploy/fab/dropq_environment.yml` file (which no long has a bokeh requirement)?

@MattHJensen @brittainhard

**Comment by hdoupe** [comment]
@brittainhard and I discussed making the environment setup files clearer.  Upon doing this, there should definitely be tests to make sure we are running the correct versions of packages.

@martinholmer I'm not sure why they are in different files.
