### ISSUE TITLE
Add preset for Brown-Khanna GAIN Act

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#704]
TaxBrain should add a preset for the Brown-Khanna GAIN Act, which calls for a major EITC expansion.

@MattHJensen requested this in [Tax-Calculator issue 1552](https://github.com/open-source-economics/Tax-Calculator/issues/1552).  The JSON reform file for that reform is now available at `taxcalc/reforms/BrownKhanna.json`.

All that is left to do is for TaxBrain to add it to the bottom of the `Presets` list in the `Get Started` section.

![screen shot 2017-10-12 at 11 20 13 am](https://user-images.githubusercontent.com/12170745/31521781-cebd9c3e-af78-11e7-9f49-19e6beec48bd.png)

**Comment by hdoupe** [comment]
@martinholmer This should be an easy addition for 1.1.0.  Two more things are needed though:

1. Reform - a link to the edit parameters page with reform values filled in. For example: Clinton [link](https://www.ospc.org/taxbrain/edit/11179/?start_year=2017)
2. Notes - a google doc with a more human readable summary of the reform. For example: Clinton [notes](https://docs.google.com/document/d/1B3VhYhOtDRR5Q613vyiV236TOmqvnn29E9APYk-mll4/edit)

**Comment by martinholmer** [comment]
@hdoupe said in #704 that we need:
> Notes - a google doc with a more human readable summary of the reform.

With respect to the Notes, can you just point to a PDF?
See the links in the original post by @MattHJensen in [Tax-Calculator issue 1552](https://github.com/open-source-economics/Tax-Calculator/issues/1552).

**Comment by travelmail26** [comment]
This is great! Two notes

1. i had issues doing the eitc because i couldnt figure out how to indicate both kink points. Khannas plan has an end to the phase in and an end to phase out. this is what should give the EITC is flattop trapezoid shape. in the bill, khanna has these points

2. booker also released his bill with an EITC and CTC

https://www.baldwin.senate.gov/imo/media/doc/The%20Stronger%20Way%20Act%20Backgrounder.pdf

Might be worth adding so tax plans can be compared

**Comment by hdoupe** [comment]
@martinholmer said
> With respect to the Notes, can you just point to a PDF?

This is my understanding of the usefulness of creating a separate notes document.  The notes document is helpful because it is a human readable document that indicates which parts of the reform we were able to model and what had to be excluded.  Also, a link to the original document is listed in the notes.

**Comment by martinholmer** [comment]
@hdoupe,  Concerning issue #704, there is a broader problem here.  Like a number of other things in the PolicyBrain application, the "Presets" section is not part of the PolicyBrain repository.

The first step in resolving #704 is to **move everything having to do with the PolicyBrain application into the PolicyBrain repo**, as we have discussed many times (see [open issue 664](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/664#issuecomment-331488312) and [closed issue 685](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/685), for a couple of examples of this recurring problem).

The second step is make TaxBrain read the `taxcalc/reforms/*.json` file of each preset reform in order to get the values of policy parameters for the TaxBrain GUI input page.  There should be no duplication of the specification of the reform in the PolicyBrain repo. (Maybe this is already the way TaxBrain works, but I can't tell because the "Preset" text is not in the repo.)

This strategy will add to the repo:
1. The "Presets" text, which now is apparently in the secret Django account
2. The notes for each report, which now is in some (many?) Google Docs accounts.

@MattHJensen @GoFroggyRun

**Comment by hdoupe** [comment]
@martinholmer I agree with you.  These documents need to be moved into the PolicyBrain repo.  Currently, they are in the admin portion of the Django site.

@GoFroggyRun I can give you access to these files.  Would you mind moving them into the PolicyBrain repo?

**Comment by GoFroggyRun** [comment]
@martinholmer said:
>The first step in resolving #704 is to move everything having to do with the PolicyBrain application into the PolicyBrain repo, as we have discussed many times (see open issue 664 and closed issue 685, for a couple of examples of this recurring problem).

and @hdoupe replied:
> I agree with you. These documents need to be moved into the PolicyBrain repo. Currently, they are in the admin part of the Django site.

+1 here. 

@martinholmer also said: 
>The second step is make TaxBrain read the taxcalc/reforms/*.json file of each preset reform in order to get the values of policy parameters for the TaxBrain GUI input page. There should be no duplication of the specification of the reform in the PolicyBrain repo. (Maybe this is already the way TaxBrain works, but I can't tell because the "Preset" text is not in the repo.)

By looking at the website element, those reforms seem merely pre-edited TaxBrain hyper links. I agreed that "there should be no duplication of the specification of the reform in the PolicyBrain repo."

**Comment by GoFroggyRun** [comment]
@hdoupe said: 
>I can give you access to these files. Would you mind moving them into the PolicyBrain repo?

No problem.

**Comment by hdoupe** [comment]
@GoFroggyRun great, thanks. I just emailed the necessary info over to you so that you can get started.

**Comment by hdoupe** [comment]
With the merge of #711, we can easily add this preset.  Here's a link to the edit parameter page for this run: https://www.ospc.org/taxbrain/edit/19212/?start_year=2017

@martinholmer would you mind putting together a reform notes document like this one: https://docs.google.com/document/d/1B3VhYhOtDRR5Q613vyiV236TOmqvnn29E9APYk-mll4/edit?

Upon creating this reform notes document, we can add this reform as a preset.

**Comment by martinholmer** [comment]
@hdoupe said:
> With the merge of #711, we can easily add this preset. Here's a link to the edit parameter page for this run: > https://www.ospc.org/taxbrain/edit/19212/?start_year=2017
>
> @martinholmer would you mind putting together a reform notes document like this one: 
> https://docs.google.com/document/d/1B3VhYhOtDRR5Q613vyiV236TOmqvnn29E9APYk-mll4/edit?
>
> Upon creating this reform notes document, we can add this reform as a preset.

It's great that #711 moved the secret HTML code into the PolicyBrain repository (thanks, @GoFroggyRun, for doing that), but the preset Notes are still not in the PolicyBrain repository.  I thought we had decided to move **everything** out of secret places into the public repository?

**Comment by martinholmer** [comment]
@hdoupe,  It seems as if the Notes for each preset reform should be in a markdown document that is in the PolicyBrain repository.  You can copy and paste into the PolicyBrain repo the `BrownKhanna.md` file included in [Tax-Calculator pull request 1607](https://github.com/open-source-economics/Tax-Calculator/pull/1607).

I'll leave it up to the PolicyBrain developers to translate the Google Docs into markdown files in the PolicyBrain repository.

**Comment by hdoupe** [comment]
@martinholmer Thank you for your contribution in creating the notes file.  I agree with you that the current system is sub optimal, but I hesitate to make this change for two reasons.

1.  We are releasing today and time is tight.  Thus, while we could just use a link to the mark-down file that you made, we do not have enough time to translate the other files before release.
2. This is a major change from our current system.  I think that we should open up an issue and discuss the best way to display these files.  It may be that your solution is the one that we choose.  However, we should reach a consensus before we move to a new reform notes system.

Does this sound sensible?

**Comment by martinholmer** [comment]
Yes. I didn’t think you would make the change immediately.
