### ISSUE TITLE
Add CCC video to getting started page

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#719]
@jessmc, I'm just looking over #698 on the test app and see that there is only a TaxBrain video on the getting started page and no CCC video. Could you add the CCC video in a followup PR? I believe we provided that to you, but please let me know if we didn't! 

cc @mikejpratt @jdebacker @hdoupe

**Comment by mikejpratt** [comment]
I don’t think it had been finished when I sent them the assets. If you provide I’ll make sure the right folks have it.

Michael J. Pratt
Director, Digital Strategy
P: 202.862.5823<tel:202.862.5823> C: 202.695.5776<tel:202.695.5776>
aei.org<http://www.aei.org/> | @mikejpratt<https://twitter.com/mikejpratt>

On Oct 27, 2017, at 5:12 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:


@jessmc<https://github.com/jessmc>, I'm just looking over #698<https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/698> on the test app and see that there is only a TaxBrain video on the getting started page and no CCC video. Could you add the CCC video in a followup PR? I believe we provided that to you, but please let me know if we didn't!

cc @mikejpratt<https://github.com/mikejpratt> @jdebacker<https://github.com/jdebacker> @hdoupe<https://github.com/hdoupe>

**Comment by MattHJensen** [comment]
@ecbrown5, could you send the CCC video to @mikejpratt.

**Comment by hdoupe** [comment]
Resolved by #724. See https://www.ospc.org/getting-started/
