### ISSUE TITLE
Dynamic model for welfare

### ISSUE THREAD

**Issue by travelmail26** [OpenSourcePolicyCenter/PolicyBrain#720]
Kind of an offbeat question/request: say we wanted to create a new dynamic score based on the macro stimulus from welfare spending (perhaps how an EITC would reduce poverty and generate consumption). 

https://www.americanprogress.org/issues/economy/reports/2014/03/31/86693/the-safety-net-is-good-economic-policy/

How much do you think it would cost to hire an economist to take an existing model and apply it to one of the dynamic ones on taxbrain?

**Comment by MattHJensen** [comment]
Thanks for your interest in the project! OSPC does not conduct contract research, although you are welcome to contact individual contributors. Closing.
