### ISSUE TITLE
Production app dropdown headers are not working

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#726]
The drop-down headers are not working properly.  Instead of dropping down when you hover over them, they are just displayed like:

<img width="838" alt="screen shot 2017-11-02 at 10 11 03 pm" src="https://user-images.githubusercontent.com/9206065/32358229-be01a5b8-c01a-11e7-925f-c40f6877d1ef.png">

The test app headers work just fine.  The flat-blocks files are still in the django admin part of the site.  Perhaps, removing them would fix this.  I'm not sure what else would cause this problem.

cc @GoFroggyRun @MattHJensen

**Comment by MattHJensen** [comment]
They are fine on my machine running chrome. 
![image](https://user-images.githubusercontent.com/8301092/32358397-1a823810-c01c-11e7-875d-284549e1b2eb.png)

**Comment by hdoupe** [comment]
Ah ok, they work fine on safari, too.  This must be a Firefox issue.

**Comment by GoFroggyRun** [comment]
@hdoupe I had similar problem. But everything works just fine in an incognito window. 
My guess is that browser's cache is messing things up.

**Comment by hdoupe** [comment]
For some reason the drop down headers work in Firefox now.

**Comment by MattHJensen** [comment]
> For some reason the drop down headers work in Firefox now. 

Probably a cache issue as @GoFroggyRun suspected.

**Comment by hdoupe** [comment]
Yep, I cleared my cache yesterday.  Thanks @GoFroggyRun
