### ISSUE TITLE
Incorrect hover-over figures shown on initial render of bubble plot

### ISSUE THREAD

**Issue by hayleefay** [OpenSourcePolicyCenter/PolicyBrain#728]
I recently noticed that my bubble plot visualization shows the incorrect figures in the hover over feature on the initial render.

<img src="https://user-images.githubusercontent.com/12599305/32359689-cc44e51a-c01d-11e7-9dbb-2979bc30669a.png" width="600"/>

As soon as another option is chosen in the buttons below the plot, the correct figures are shown for all options, including the initially incorrectly rendered option.

I'll work on fixing this as soon as possible.

**Comment by hdoupe** [comment]
Thanks @hayleefay.  Can you also take a look at the horizontal axis label?  When you select a different tab  from METTR, METR, Cost of Capital, or Depreciation, the label doesn't change. 

<img width="1071" alt="screen shot 2017-11-08 at 9 58 10 am" src="https://user-images.githubusercontent.com/9206065/32555644-5dde8638-c46b-11e7-944e-589e14e7e1a3.png">

**Comment by hdoupe** [comment]
Closed via #742
