### ISSUE TITLE
Non-weighted output tables, "All" row missing results

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/PolicyBrain#73]
In the results tables that aren't the weighted averages, the bottom row (corresponding to all filers) appears to be missing results for the following three columns:
1) Average Tax Change
2) Percent with a Tax Increase
3) Percent with a Tax Decrease

**Comment by talumbau** [comment]
@jdebacker is this still relevant and would you say it is a bug? cc @MattHJensen

**Comment by hdoupe** [comment]
@MattHJensen @martinholmer this appears to still be an issue.  What do you think?

![screen shot 2017-11-28 at 11 05 55 am](https://user-images.githubusercontent.com/9206065/33330208-3f23c412-d42c-11e7-803c-d484ae538d0f.png)

**Comment by MattHJensen** [comment]
I agree this is still an issue. I am adding a bug label since 0s are inaccurate.

**Comment by martinholmer** [comment]
[Tax-Calculator pull request 1705 ](https://github.com/open-source-economics/Tax-Calculator/pull/1705) added the "All" value for the `mean` statistic generated by the `create_difference_table` utility function.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I agree this is still an issue. I am adding a bug label since 0s are inaccurate.

But the current 0.13.2 release of Tax-Calculator sets those All values to NaN.
Why is TaxBrain showing a zero when the value is NaN?

@hdoupe @GoFroggyRun

**Comment by martinholmer** [comment]
Issue #73 has been resolved on the Tax-Calculator side in [pull request 1741](https://github.com/open-source-economics/Tax-Calculator/pull/1741), but there still need to be changes in TaxBrain to resolve this issue completely.

**Comment by hdoupe** [comment]
Resolved via open-source-economics/Tax-Calculator#1741.

Difference table for [TCJA_Senate_111417.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Senate_111417.json), year 2020:

![screen shot 2017-12-11 at 11 07 14 am](https://user-images.githubusercontent.com/9206065/33840905-3cd9950a-de64-11e7-8b59-b873e50c4109.png)

cc @martinholmer

**Comment by hdoupe** [comment]
Closed #73

**Comment by hdoupe** [comment]
Closed #73
