### ISSUE TITLE
PolicyBrain tab link back to homepage

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#732]
It seems intuitive to me for the "PolicyBrain" tab to link back to the home page, www.ospc.org.  

@MattHJensen @GoFroggyRun  what do you think?

![screen shot 2017-11-08 at 11 18 49 am](https://user-images.githubusercontent.com/9206065/32560135-cb5b9d4e-c476-11e7-9512-e147f62c3258.png)

**Comment by GoFroggyRun** [comment]
The logo on the left seems to be a link to the home page ospc.org.

**Comment by hdoupe** [comment]
Right, but the first time I used the new version of the website, I clicked "PolicyBrain" thinking it would take me back to the home page.  This makes me think that other people might do the same thing.  I don't see anything wrong with having multiple links back to the home page.

**Comment by GoFroggyRun** [comment]
Ahh. I see. You meant we ought to have another link to ospc.org embedded within the "PolicyBrain" button? That makes sense to me.

**Comment by hdoupe** [comment]
Resolved via #741
