### ISSUE TITLE
Some links not working in the "As Seen In" section

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#736]
In the "As Seen In" section on OSPC's home page, a couple links seem to be removed and thus are not working. In particular, Barron's and OpportunityLives both links yield some "404 Error" page when clicked. 
 
<img width="917" alt="screen shot 2017-11-09 at 7 49 32 pm" src="https://user-images.githubusercontent.com/13324931/32637321-23411708-c587-11e7-9cba-e0caac5d7c7a.png">

**Comment by MattHJensen** [comment]
This should also include the New York Times and Forbes.

**Comment by GoFroggyRun** [comment]
@MattHJensen do you happen to have links to the articles in NYT and Forbes? 
I was able to find a link to Barron's [article](http://www.barrons.com/articles/social-securitys-predictions-1431129373), but the link to OpportunityLives is still missing. Do you happen to have it as well?

**Comment by MattHJensen** [comment]
@GoFroggyRun, given that there have been many articles in many of these sources, I'd be inclined to remove links entirely

**Comment by GoFroggyRun** [comment]
@MattHJensen makes sense to me.
