### ISSUE TITLE
link to ospc.org/hello from ospc.org/docs broken

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#737]
Moving https://github.com/open-source-economics/Tax-Calculator/issues/1640 to PolicyBrain. 

@maxghenis said:

> https://www.ospc.org/docs/ links to https://ospc.org/hello ("leave a note for the OSPC team"). This link doesn't work.

> Ah, it needs www: https://www.ospc.org/hello works.

**Comment by hdoupe** [comment]
Closed via #741
