### ISSUE TITLE
Add CPS button

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#740]
@GoFroggyRun The two most recent commits in PR #738 ([nested_form_parameters are grayed out](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/738/commits/f5910bc8f46811e6f5b4da7e8bb726fc58920633) and [Look for puf_not_cps flag in views.py](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/738/commits/4d99a32654fc2001f6c487bfd33d90dcf3901ba3)) add the back-end capabilities to handle a "use cps" flag.

I'm not exactly sure what we need to do to add this to the front-end.  I think it would work something like the "change start year" action where the page is refreshed with a different start year.  So, you would click a "use cps" button, the page would refresh but would include only parameters that are compatible with the CPS.  I'm open to other approaches though.

**Comment by MattHJensen** [comment]
Ideally we'll 'gray out' rather than eliminate params that don't work with a given dataset.

**Comment by hdoupe** [comment]
In that case, I think it would make sense to add a flag attribute, `gray_out`, to the `TaxCalcParam` object.  That would be "on" when parameters that are compatible with the CPS but not the PUF when the PUF data set is selected and vice versa.  I'll update PR #738. 

This attribute can be accessed in the html and javascript files I think.

**Comment by GoFroggyRun** [comment]
@hdoupe thanks for the updates in #738. 

As @MattHJensen pointed out, the way that I have in mind is to display all parameters while grey out certain ones that are not compatible with the dataset selected. A flag attribute sounds sufficient.

**Comment by hdoupe** [comment]
@GoFroggyRun I made the changes in PR #738 that add the graying out attribute.

**Comment by martinholmer** [comment]
@hdoupe,  Note that using the `cps.csv` data file on TaxBrain will **not** work correctly until the data bug in the `cps_weights.csv` file is fixed in the taxdata repo and used in the Tax-Calculator repo.  

See [taxdata issue 125](https://github.com/open-source-economics/taxdata/issues/125#issuecomment-346891030) for details.

**Comment by hdoupe** [comment]
Closed via #835, #842
