### ISSUE TITLE
UBI Parameters are displayed and they should not be

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#746]
The GUI interface is displaying the UBI parameters when it should not be.

**Comment by martinholmer** [comment]
@hdoupe said:
> The [TaxBrain] GUI interface is displaying the UBI parameters when it should not be.

All I know is that @MattHJensen activated the UBI policy parameters in [Tax-Calculator pull request 1599](https://github.com/open-source-economics/Tax-Calculator/pull/1599).

**Comment by hdoupe** [comment]
Thanks @martinholmer, but we need the CPS to use those parameters.  We haven't had time to put that up yet.

**Comment by MattHJensen** [comment]
@hdoupe, my understanding based on conversation with with @andersonfrailey is that the CPS is not needed for the UBI parameters. My work in #1614 confirms this: https://github.com/open-source-economics/Tax-Calculator/pull/1614/files#diff-496bf0f0853ae02da9e238398f213913L4473

**Comment by hdoupe** [comment]
@MattHJensen Ok, I see.  That makes sense.  You just can't simulate the benefits repeal, correct?

**Comment by MattHJensen** [comment]
> You just can't simulate the benefits repeal, correct?

Correct.

**Comment by hdoupe** [comment]
Cool, so we will leave the parameters up?

**Comment by MattHJensen** [comment]
> Cool, so we will leave the parameters up?

Yep.

**Comment by hdoupe** [comment]
Great thanks.
