### ISSUE TITLE
TaxBrain reform hanging

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#750]
![image](https://user-images.githubusercontent.com/8301092/33081103-6c1e4896-cea7-11e7-8d95-57fbc803a315.png)

When I run this simulation, it hangs on "a few seconds left" 

@hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
@MattHJensen I've had issues with this locally when I've had many things going on my computer.  This leads me to believe that it's a memory problem.  I'll look into this further.

**Comment by GoFroggyRun** [comment]
@MattHJensen are you on test app? I just ran this reform on ospc.org: https://www.ospc.org/taxbrain/22266/

**Comment by MattHJensen** [comment]
I am on the test app. I was just able to run it successfully as well on the test app.

**Comment by hdoupe** [comment]
@MattHJensen It ran successfully, but it loaded the "few seconds left" page for a minute or two first, right?

**Comment by MattHJensen** [comment]
Exactly.

**Comment by hdoupe** [comment]
Ok, I'll see if I can get this to work.

**Comment by hdoupe** [comment]
It looks like the run-time is just incredibly slow.  Thus, TaxBrain thinks the results should be ready, but they aren't.  Here's output from the test server:

Previous version of PolicyBrain:
```
[2017-10-30 20:15:21,992: WARNING/MainProcess] elapsed time for this run:
[2017-10-30 20:15:21,992: WARNING/MainProcess] 15.4253900051
```

Pre-release Version:
```
[2017-11-20 21:43:42,614: WARNING/MainProcess] elapsed time for this run: 39.6
```
