### ISSUE TITLE
Extra "Total" options and none of them work

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#758]
The TaxBrain results page has a drop down menu for the difference and distribution tables.  This menu allows the user to view results for each of the budget years.  Currently, there are three `Total` options and all of them produce a blank table.

<img width="1128" alt="screen shot 2017-11-30 at 10 37 29 am" src="https://user-images.githubusercontent.com/9206065/33439158-c1475ab4-d5ba-11e7-802c-d0b631a08052.png">

cc @GoFroggyRun

**Comment by GoFroggyRun** [comment]
When are these "Total"s being added? I haven't made any changes to the build table codebase for a couple releases.

**Comment by hdoupe** [comment]
Closed via #783
