### ISSUE TITLE
Include graphs in the Tax Brain results

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/PolicyBrain#76]
Consider presenting some graphs to summarize results.  

One suggestion is to have the 10 year numbers headline (as they do), next display some graphs, then include the detailed tables currently shown.  

Graphs might be the percent change in taxes (or dollar change in taxes per filer) by decile/income group (e.g. as a bar graph), a histogram of the dollar or percent changes over finer bins of percentiles or income, or something else.  But users who don't already spend time looking at budgetary tables could perhaps benefit from an easier way to visualize the results.

**Comment by talumbau** [comment]
@MattHJensen can you assign this a milestone or close?

**Comment by hdoupe** [comment]
Graphs would be nice to include in the results, but I don't think we have the bandwith to work on this any time in the near future.

**Comment by hdoupe** [comment]
Closed #76
