### ISSUE TITLE
File upload change start year directs to GUI input page

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#760]
If you select a different start year for the file upload page, then it directs you to the GUI input page with this new start year.  But, if you press the back button, it takes you to the file upload page with the new start year.

The correct behavior should be a redirect to the file upload page with the new start year.

**Comment by MattHJensen** [comment]
Note that even after you press the back button and get to the start year you selected, that new start year is not actually used when you run the simulation. 

Similarly, if I go to https://www.ospc.org/taxbrain/file/?start_year=2018 and submit a reform, the simulation will still start in 2017.

**Comment by hdoupe** [comment]
> Note that even after you press the back button and get to the start year you selected, that new start year is not actually used when you run the simulation.

Yes, this is correct.  Going back does not actually change the start year.  But it does change the value in drop-box.

> Similarly, if I go to https://www.ospc.org/taxbrain/file/?start_year=2018 and submit a reform, the simulation will still start in 2017.

Clicking this link and submitting a reform worked fine for me:
- Quick-calc: https://www.ospc.org/taxbrain/23973/
- Full-calc: https://www.ospc.org/taxbrain/23975/

**Comment by hdoupe** [comment]
This leads me to believe that this is a front-end bug since the link works if you enter it manually.  However, if you click the button, you are re-directed to the wrong page. 

I think that the relevant sections of code are:
- [templates/taxbrain/input_file.html](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/templates/taxbrain/input_file.html#L187-L204)
- [static/js/filetb.js](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/static/js/filetb.js#L79-L83)

@GoFroggyRun what do you think?

**Comment by MattHJensen** [comment]
When I go to https://www.ospc.org/taxbrain/file/?start_year=2018 and submit the senate json I get https://www.ospc.org/taxbrain/23977/. Liabilities table should start in 2018. 

Perhaps the edge case is when the reform starts in 2017 and the analysis/table should start later??

**Comment by hdoupe** [comment]
@GoFroggyRun I agree that the redirection is a front-end problem and that the warning page business is a backend problem.  I'll get started on the warning page.  Do you have time to take a look at the redirect problem?

**Comment by GoFroggyRun** [comment]
@hdoupe probably not today. When to you plan to make a new release?

**Comment by hdoupe** [comment]
Ok, sounds good.  Sometime next week I think.

**Comment by hdoupe** [comment]
Closed via #767
