### ISSUE TITLE
warnings on taxbrain/file clear input files

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/PolicyBrain#761]
When I upload, for instance, the senate json reform file at taxbrain/file and then click "Show me the results," I get a series of warnings. 

At this point I should be able to click show me the results again to ignore the warnings, but I can't because the reform file I uploaded has been cleared out. 

If I click choose file, reselect the file, and then click run, everything works. 

I shouldn't have to reselect the file. 

This happens on both Chrome and Firefox. Both reform and assumption files are cleared by warnings.

**Comment by hdoupe** [comment]
@MattHJensen Ok, I see what you mean.  I'll get started on this after #760.
