### ISSUE TITLE
Legend for bubble plot

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/PolicyBrain#764]
@martinholmer asks:

> When first looking at the "bubble plot" on the results page of the CCC, I didn't see where the meaning of the size of the bubble was explained. Did I miss the explanation? What does the size of the bubble mean?

The bubble sizes are based on the amount of assets of that type (or in that industry).  We should probably add a legend for this to the plot so it's clear.  An example can be found from [this widget](https://www.ospc.org/gallery/corp_mettr/) in the OSPC gallery.

cc @hayleefay

**Comment by martinholmer** [comment]
@jdebacker said:
>> When first looking at the "bubble plot" on the results page of the CCC, I didn't see where the meaning of the size of the bubble was explained. Did I miss the explanation? What does the size of the bubble mean?
>
> The bubble sizes are based on the amount of assets of that type (or in that industry). We should probably add a legend for this to the plot so it's clear. An example can be found from this widget in the OSPC gallery.

OK, thanks for the explanation.  But is the "amount of assets" proportional to the **diameter** of the circle or the **area** of the circle?  The size of a circle can have two different meanings.

**Comment by hdoupe** [comment]
@hayleefay @andersonfrailey are you interested in tackling this issue?

**Comment by andersonfrailey** [comment]
I can take a crack at it

**Comment by hdoupe** [comment]
@andersonfrailey Awesome, thanks. See #642 for the original work. Let me know if there's anything else I can do to help you get started.

**Comment by andersonfrailey** [comment]
@jdebacker, what should each size bubble be labeled?

**Comment by jdebacker** [comment]
@andersonfrailey I don't think the sizes are predetermined.  Rather, I there is a different bubble size for  each of 15 quantiles.  See [here](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/ecb46daa0322b39d1c5c3b192d3a9928db5aca03/webapp/apps/btax/bubble_plot/bubble_plot_tabs.py#L39).  

I'd recommend labeling only the smallest and largest bubbles as done [here](https://www.ospc.org/gallery/corp_mettr/) so as not to make the legend too busy.

@hayleefay might have other suggestions are the creator of this particular plot.

**Comment by andersonfrailey** [comment]
How's this look:
![screen shot 2018-01-18 at 3 31 57 pm](https://user-images.githubusercontent.com/20684675/35120012-bf911536-fc64-11e7-95e6-00a7c795415c.png)

**Comment by jdebacker** [comment]
@andersonfrailey Looks pretty good.  I think some text to say that those are amount of assets on the label could be helpful.

Also, I might try to locate it on top (or bottom) of the graph since horizontal space is more limited than vertical space when displayed on the screen.

**Comment by andersonfrailey** [comment]
![screen shot 2018-01-18 at 4 53 31 pm](https://user-images.githubusercontent.com/20684675/35123424-1c5b6f54-fc70-11e7-8917-59ff71ecb256.png)
@jdebacker how's this?

**Comment by jdebacker** [comment]
@andersonfrailey Looks good to me!  Nicely done.

**Comment by hayleefay** [comment]
@andersonfrailey @hdoupe @jdebacker I'm sorry I have been MIA for this issue. That looks great, Anderson. The plot was modeled after the one Jason linked so that is definitely the correct legend.

**Comment by hdoupe** [comment]
@andersonfrailey, @hayleefay, @jdebacker Thanks for your work on this issue.

**Comment by hdoupe** [comment]
Closed #764
