### ISSUE TITLE
Handle future year reforms for checkboxes

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/PolicyBrain#765]
There's one provision in TCJA Senate Modified Mark's proposal that introduces "stack[ing] the dependent credit before the child tax credit" in 2018, and then repeals it starting 2026. 

Currently, this boolean parameter `_DependentCredit_before_CTC` is handled using a checkbox on TaxBrain: checked box indicates true while unchecked one represents false, which I believe is a concise way of integrating such boolean parameters. It seems that, however, such format won't allow users to specify any further reforms for future years.  

Since it would be desirable to handle both House and Senate reforms in TaxBain's GUI, we might want to modify, at least for `_DependentCredit_before_CTC` parameter, the way of handling boolean fields to allow future year reforms. However, I haven't come up with an ideal way to deal with it. 

Any comments, concerns or remarks would be helpful. @martinholmer @MattHJensen @hdoupe

**Comment by hdoupe** [comment]
Do you think we should add a "Byrd Rule" switch that reverts changes to the default after 10 years?  We could present it the same way as the cpi buttons. 
![screen shot 2017-12-06 at 1 29 33 pm](https://user-images.githubusercontent.com/9206065/33678366-87da17a2-da89-11e7-8451-b71934302145.png)

**Comment by martinholmer** [comment]
@hdoupe said:
> Do you think we should add a "Byrd Rule" switch that reverts changes to the default after 10 years?

I don't know what the "Byrd Rule" is.  Exactly how would it help resolve issue #765?

The fundamental problem @GoFroggyRun pointed out in #765 is that any policy parameter represented in TaxBrain with a check box has no time dimension.  So, unlike in Tax-Calculator, it can't be turned off or on in any year.  As far as I can see, the only way for TaxBrain to have the same flexibility as Tax-Calculator has in changing policy parameters year by year, would be for TaxBrain to convert all check boxes to text boxes just like all the other one-dimensional parameters like `_II_em` or `_SS_Earnings_c`.

**Comment by hdoupe** [comment]
Sorry, I shouldn't have used Byrd Rule. I don't really know what it means.  I just hear it in conjunction with policy changes that are reverted back to the default after 10 years or so.  This seems like a common maneuver to satisfy budget rules.  I was thinking that we could have a switch similar to the CPI button that reverts these changes back after 10 years.  

However, this isn't a very good solution.  It would be best for the user to have the flexibility to turn switches on or off after x years.  x being 3 or 10 shouldn't matter.

@martinholmer  said
> As far as I can see, the only way for TaxBrain to have the same flexibility as Tax-Calculator has in changing policy parameters year by year, would be for TaxBrain to convert all check boxes to text boxes just like all the other one-dimensional parameters like _II_em or _SS_Earnings_c.

This could work, and I can't think of another solution either.  My only objection is that it may not be obvious whether the user is supposed to enter a binary value such as 0/1 or True/False, or a numeric value.

**Comment by MattHJensen** [comment]
@hdoupe:

> This could work, and I can't think of another solution either. 

Agreed. 

> My only objection is that it may not be obvious whether the user is supposed to enter a binary value such as 0/1 or True/False, or a numeric value.

I suppose we'd have to update the user instructions at the top of the page. The user would also see the default value, so that would be a strong hint.

**Comment by hdoupe** [comment]
@MattHJensen said
> I suppose we'd have to update the user instructions at the top of the page. The user would also see the default value, so that would be a strong hint.

Ok, that makes sense.

Converting the checkbox parameters to text box parameters should be an easy change to make.  The only part that I am worried about is that we have to change the data type for these parameters in the database.  Given my [previous misadventures](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/743) with altering the database, I plan to proceed with caution while doing this.

**Comment by hdoupe** [comment]
I'm going to keep #765 open until all of the boolean parameters are presented in a comma separated format.

**Comment by hdoupe** [comment]
Closed via #822

**Comment by hdoupe** [comment]
Closed via #822
