### ISSUE TITLE
See the two issues raised by user involving TaxBrain problems

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#768]
[Tax-Calculator issue 1736](https://github.com/open-source-economics/Tax-Calculator/issues/1736) and [Tax-Calculator issue 1737](https://github.com/open-source-economics/Tax-Calculator/issues/1737) report problems a user is having with TaxBrain.

Part of these problems are caused by Tax-Calculator and I'll handle those enhancements.

@hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
I broke the part of this issue related to the warning/error messages into #769.  The part of this issue related to the incorrect "All" values is already addressed in #73.

@martinholmer Is it ok if I close this? Or, would you like to leave it open until both issues are resolved?

**Comment by martinholmer** [comment]
It's fine to close #768.  I plan to fix T-C wrt issue #73 in the next day or two.

**Comment by hdoupe** [comment]
Ok, thanks @martinholmer
