### ISSUE TITLE
PolicyBrain 1.2.1

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#772]
PolicyBrain 1.2.1 will be released either tonight or tomorrow.  Issues to be tackled:

- NA - ID_AmountCap_Switch not consistently set as 1/0 (resolved via #757)
- #306 and #747 - Back-to-back quick calc submissions and correct description (resolved via #759) 
- #761 - warnings on taxbrain/file clear input files (resolved via #762)
- #760 - File upload change start year directs to GUI input page (resolved via #766 and #767)

Some of the quick items from #769 can also be tacked on if there is timely feedback.  The file upload page will require some follow up PR's. Since #762 and #767 are ready to go and these are glaringly bad bugs, I plan to push these fixes up as soon as possible.

cc @GoFroggyRun @MattHJensen @martinholmer

**Comment by martinholmer** [comment]
I was thinking there might be a Tax-Calculator release in the next day or so.
Does that affect your thinking about the timing of the next PolicyBrain release?

**Comment by hdoupe** [comment]
Thanks @martinholmer. It looks like the only change that will require work on the PolicyBrain side is a new parameter, `_CTC_new_refund_limited_all_payroll`.  That should be an easy update. We can wait on the next Tax-Calculator release.

**Comment by martinholmer** [comment]
@hdoupe said:
>  It looks like the only change that will require work on the PolicyBrain side is a new parameter, `_CTC_new_refund_limited_all_payroll`. That should be an easy update. We can wait on the next Tax-Calculator release.

OK.  Thanks for the quick response.

**Comment by hdoupe** [comment]
PolicyBrain 1.2.1 has been released and is in production.

**Comment by hdoupe** [comment]
Closing #772
