### ISSUE TITLE
500 Error when invalid parameter is used

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#779]
In open-source-economics/Tax-Calculator#1771, @MaxGhenis found that you get a 500 error if you upload a reform file with an invalid parameter name.  I submitted the same reform on the test app.  This is the feed back that was given:

<img width="682" alt="screen shot 2017-12-18 at 11 39 14 am" src="https://user-images.githubusercontent.com/9206065/34116954-1b50011a-e3e8-11e7-8a12-5274eaf58fca.png">
<img width="835" alt="screen shot 2017-12-18 at 11 39 58 am" src="https://user-images.githubusercontent.com/9206065/34117219-03624fee-e3e9-11e7-90d0-d8627f6e2493.png">

PolicyBrain expects a numerical year value for all keys in the errors/warning dictionary.  Supplying an invalid parameter results in there being a key, "invalid."  This should be fixed.

Thanks for the bug report @MaxGhenis.

**Comment by hdoupe** [comment]
After giving this issue some more thought, I think that this issue exposes a deeper problem with the warning and error message processing and parsing.  Currently, the PolicyBrain function that parses the errors and warnings, [`parse_errors_warnings`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views.py#L155), uses pretty simple logic to parse the strings provided by Tax-Calculator.  However, the message given here has a slightly different format and causes a value error:

`"ERROR: invalid parameter name _ID_AllTaxes_c in 2018\n"`

The expected format is:
`"Action: year param_name message"`

For example, this reform
```
{'behavior': {},
 'consumption': {},
 'growdiff_baseline': {},
 'growdiff_response': {},
 'policy': {2018: {'_II_brk2': [[0, 77400, 38700, 51800, 77400]]}}}
```
causes
```
In [24]: ew = taxcalc.tbi.reform_warnings_errors(policy_dict)

In [25]: ew
Out[25]: 
{'errors': 'ERROR: 2018 _II_brk2_0 value 0.0 < min value 9534.81 for _II_brk1_0\nERROR: 2019 _II_brk2_0 value 0.0 < min value 9748.39 for _II_brk1_0\nERROR: 2020 _II_brk2_0 value 0.0 < min value 9973.58 for _II_brk1_0\nERROR: 2021 _II_brk2_0 value 0.0 < min value 10210.95 for _II_brk1_0\nERROR: 2022 _II_brk2_0 value 0.0 < min value 10459.08 for _II_brk1_0\nERROR: 2023 _II_brk2_0 value 0.0 < min value 10706.96 for _II_brk1_0\nERROR: 2024 _II_brk2_0 value 0.0 < min value 10963.93 for _II_brk1_0\nERROR: 2025 _II_brk2_0 value 0.0 < min value 11224.87 for _II_brk1_0\nERROR: 2026 _II_brk2_0 value 0.0 < min value 11492.02 for _II_brk1_0\nERROR: 2027 _II_brk2_0 value 0.0 < min value 11767.83 for _II_brk1_0\n',
 'warnings': ''}

In [26]: ew['errors'].split('\n')[0]
Out[26]: 'ERROR: 2018 _II_brk2_0 value 0.0 < min value 9534.81 for _II_brk1_0'

```

I think that we should decide on either a standard message format or come up with a better way to deliver the data required by PolicyBrain.  The required data is the message action ("ERROR", "WARNING"), year that the parameter causes the action, and the message itself.  If we do not do do something now, then it seems like PolicyBrain developers will continue to alter the message parsing function and this function will become harder to understand and maintain.

One solution would be to add a verbose option that returns a dictionary that looks like this:
```
{
    'errors': [{'year': YEAR, 'parameter_name': param_name, 'message': message}, ...], 
    'warnings': [{'year': YEAR, 'parameter_name': param_name, 'message': message}, ...]
}
```

@martinholmer do you have any thoughts on this?

**Comment by martinholmer** [comment]
@hdoupe asked about errors raised by the Policy class `implement_reform` method in PB issue #779.
He said, in part:
> Currently, the PolicyBrain function that parses the errors and warnings, parse_errors_warnings, uses pretty simple logic to parse the strings provided by Tax-Calculator. However, the message given here has a slightly different format and causes a value error [in PolicyBrain]:
>
> "ERROR: invalid parameter name _ID_AllTaxes_c in 2018\n"
>
> The expected [by PolicyBrain] format is:
> "Action: year param_name message"

Good point.  Let me try tomorrow to standardize the format of the messages in the ValueErrors raised by the Policy class `implement_reform` method.

**Comment by martinholmer** [comment]
@hdoupe, Can you review the changes in [Tax-Calculator pull request 1775](https://github.com/open-source-economics/Tax-Calculator/pull/1775)?  If they look good to you, I can merge 1775 and release 0.14.2.

**Comment by hdoupe** [comment]
Once open-source-economics/Tax-Calculator#1775 is merged, the new behavior will be:

1. Upload file with bad parameter name:
```
{
    "policy": {
        "_SS_Earnings_c": {"2018": [400000],
                           "2019": [500000],
                           "2020": [600000]},
        "_II_em": {"2018": [8000]},
        "_II_em_cpi": {"2018": false,
                       "2020": true},
        "_ALD_InvInc_ec_rt": {"2019": [0.20]},
        "_STD": {"2018": [[500, 24000, 12000, 18000, 24000]]},
        "_not_a_param": {"2018": [1000.0]}
    }
}
```
See:
![screen shot 2017-12-19 at 1 17 19 pm](https://user-images.githubusercontent.com/9206065/34172135-fa5b2b60-e4be-11e7-9c71-241067226c95.png)

2. Remove bad parameter:
```
{
    "policy": {
        "_SS_Earnings_c": {"2018": [400000],
                           "2019": [500000],
                           "2020": [600000]},
        "_II_em": {"2018": [8000]},
        "_II_em_cpi": {"2018": false,
                       "2020": true},
        "_ALD_InvInc_ec_rt": {"2019": [0.20]},
        "_STD": {"2018": [[500, 24000, 12000, 18000, 24000]]}
    }
}
```
See:
![screen shot 2017-12-19 at 1 18 27 pm](https://user-images.githubusercontent.com/9206065/34172172-234bbecc-e4bf-11e7-9f23-290403bfef06.png)

3. Submit again and the model runs.


Thanks @martinholmer for resolving this.

**Comment by hdoupe** [comment]
Closed via open-source-economics/Tax-Calculator#1775
