### ISSUE TITLE
TCJA preset

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#787]
The following enhancement request was made in [Tax-Calculator issue 1787](https://github.com/open-source-economics/Tax-Calculator/issues/1787):
> In the meantime, for TaxBrain users I would suggest adding TCJA presets to the list of presets on the TaxBrain main page (after all, it would seem to be more newsworthy at this point than any of the proposals currently listed there).

I told the requester this:
> My understanding is that they are currently working on making a TaxBrain preset for TCJA.

So, this issue is here just for the record.

**Comment by hdoupe** [comment]
#787 should be resolved via PR's #790 and #792.  @martinholmer and @siervicul I would appreciate it if you reviewed the TCJA preset on the [test app.](http://ospc-taxes7.herokuapp.com/taxbrain/edit/1512/?start_year=2018)

**Comment by martinholmer** [comment]
Issue #787 has been resolved by pull request #792.

**Comment by siervicul** [comment]
Thank you!  I notice, though, that in the links to various presets, all of the other reform proposals have a link to the actual presets and a "Notes" link, which links to a Google document with notes about which aspects of the proposal are modeled in TaxBrain and which aren't.  The TCJA links include a link to the preset and a link with the text "Notes" that actually links to TCJA_Reconciliation.json.  Would it be possible to link to a notes document for the TCJA preset like with the other reforms?  The revenue change projected by TaxBrain is very different from any other analysis I've seen (even just considering the individual side), and it would be nice to have a better idea of what is driving the difference.

**Comment by MattHJensen** [comment]
@siervicul, I'll let others address your "Notes" question. But regarding the revenue differences, have you run a partial equilibrium simulation or a purely static simulation? I expect that you can more-closely match other organizations using the partial-equilibrium features.

**Comment by siervicul** [comment]
I'm doing a static simulation, but it shows the revenue loss from the TCJA as being a little under $1.6 trillion, which about $100 billion higher than the number I've seen from other static analyses (Tax Foundation, TPC, JCT, etc.) of the _whole_ bill, including corporate cuts.
