### ISSUE TITLE
Need to remove Expanded-Income/or/Adjusted-Income row of buttons

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#796]
Now that we have decided that TaxBrain will never show distribution tables or difference tables with the AGI as the classifier variable, the expanded-income/or/adjusted-income row of buttons needs to be removed.  Here is what thinks look like in PolicyBrain 1.3.0:

![screen shot 2018-01-09 at 11 34 12 am](https://user-images.githubusercontent.com/12170745/34731889-a54daf84-f531-11e7-8284-7b199cc04d8d.png)

That third row of buttons needs to be removed.
If there is some delay in removing them, then the tool tip should be changed from "Not yet available" to "Not a choice" or "Never will be available" or something less misleading than the current text.

**Comment by hdoupe** [comment]
Thanks @martinholmer. @GoFroggyRun do you have time to take care of this?

**Comment by martinholmer** [comment]
Issue #796 has been resolved by pull request #797.
