### ISSUE TITLE
Separating revenue effects of changes to multiple tax parameters

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/PolicyBrain#80]
At some point, users will want to see revenue effects of the entire proposal separately by the various changes in tax policy.  Some thought should be given to how this might be done.  

Obviously things get more difficult to present as stacking order is important.  Are there obvious ways to stack various policies (e.g. you probably want to stack rate changes first)?  Perhaps once a default stacking order is set, the order of the parameters on the user input page could be rearranged to reflect that order.

**Comment by hdoupe** [comment]
@jdebacker This is an interesting idea. Perhaps, this could be implemented in Tax-Calculator. Can I close #80?

**Comment by MattHJensen** [comment]
+1 for opening a Tax-Calculator issue to request a feature that would generate stacked 1 or X-year revenue estimates.

**Comment by jdebacker** [comment]
@hdoupe Yes - feel free to close this issue.  Reopening one in TC when this seems feasible would be good.
