### ISSUE TITLE
Rate schedule simplification in TaxBrain?

### ISSUE THREAD

**Issue by siervicul** [OpenSourcePolicyCenter/PolicyBrain#821]
The rate schedule in the "Personal Income" section of TaxBrain is very complicated, with 36 text input fields (8 marginal rates plus 7 sets of bracket income thresholds with 4 fields each) that are duplicated in the "Regular: Non-AMT, Non-Pass-Through" and "Pass-Through" subsections.  Most reform proposals use the same rate schedules for pass-through and non-pass-through income, which means in most cases the user has to input all the same information twice (or edit all the same information twice to make tweaks to existing presets).

Would it be possible to add a "tax pass-though income the same as non-pass-through income" checkbox to the "Pass-Through" subsection?  In conjunction with the new fields for pass-through income exclusion, this would work much like the "Tax All Capital Gains And Dividends The Same As Regular Taxable Income" subsection of the "Capital Gains and Dividends" section of the form.

**Comment by hdoupe** [comment]
@siervicul Thanks for opening up this issue.

In #340, I [commented](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/340#issuecomment-358409336):
> I think that #340 works against our new approach of moving as much parameter processing as possible to the underlying model. This issue was created in response to users getting strange results due to interactions between the capital gains and AMT parameters. This seems like an issue that should be resolved by Tax-Calculator. Does PolicyBrain still need to manipulate the parameters in this way?

I feel the same way about this proposal.

@MattHJensen, @martinholmer, @GoFroggyRun what are your thoughts on this?

**Comment by hdoupe** [comment]
Closing #821 since this is out of scope for the PolicyBrain project.
