### ISSUE TITLE
Brown-Khanna GAIN Act preset problem

### ISSUE THREAD

**Issue by rickecon** [OpenSourcePolicyCenter/PolicyBrain#823]
I was trying to run the Brown-Khanna GAIN Act of 2017 [preset reform](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/BrownKhanna.json) on TaxBrain, and I got an error that says in red at the top of the page:

> Some fields have warnings or errors. Values outside of suggested ranges will be accepted if they only cause warnings and are submitted again from this page. Warning messages begin with 'WARNING', and error messages begin with 'ERROR'.

The offending cell is the *Minimum Age for Chidless EITC Eligibility*. The value that is preset on TaxBrain for the reform and which value I have tried to put in manually as well is 21. The error under this cell is:

> ERROR: _EITC_MinEligAge value 21.0 is not integer for 2017

I'm sure I can just run this using the Tax-Calculator API because the reform is working fine in my OG-USA runs. But my guess is that this is a bug in PolicyBrain. @MattHJensen @hdoupe

**Comment by hdoupe** [comment]
Thanks for the bug report @rickecon. This was also noted in #795. #822 resolves this type of problem. #822 should be in production by Tuesday or Wednesday of this week.

**Comment by hdoupe** [comment]
Closed via #822
