### ISSUE TITLE
TaxBrain error messages when adjusting standard deduction

### ISSUE THREAD

**Issue by siervicul** [OpenSourcePolicyCenter/PolicyBrain#828]
Prior to the latest update, TaxBrain used to provide a warning when reducing the standard deduction amounts below the defaults (I understand that this is due to concerns about imputing itemized deduction amounts to tax units that currently take the standard deduction).  However, the warning page would keep all amounts as entered by the user, and the user could simply click on the "show me the results" button to proceed with the lower standard deduction amounts.

Now, making _any_ changes (increase or decrease) to the default standard deduction amounts (but not apparently to the additional standard deduction amounts) with the default start year of 2017 produces a 500 internal server error.  If you change the start year to 2018 and then try to decrease the standard deduction amounts, TaxBrain provides a warning as before, but instead of retaining the values input by the user, _all_ values on the form are reset to defaults and the start year is changed to 2013.  There appears to be no way to proceed past the warning with a reduced standard deduction.

**Comment by hdoupe** [comment]
@siervicul Thanks for the bug report. PR #827 will resolve this issue. A partial solution is on the test app: http://ospc-taxes7.herokuapp.com/taxbrain/

You have to re-enter the data from your previous run, but then it should work just fine.

We are working to add back the ability to display the user inputs from the original page when showing the warning and error messages. This release changed how the input data is stored and refactored the logic for processing it. Our apologies for missing the errors/warnings case.

**Comment by hdoupe** [comment]
@siervicul Thanks for opening #828. PolicyBrain 1.4.2 resolves this issue and is running on the normal site (https://www.ospc.org/).
