### ISSUE TITLE
Create separate "maintenance" branch

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#839]
I propose that we create a separate maintenance branch for pushing small features and bug fixes. As we phase in the changes for the CPS and benefits data, we will also need to quickly apply patches as bugs are discovered. One case where this would have been useful is yesterday in #836 where a separate branch with reverted changes had to be created in order to apply a minor patch.

**Comment by martinholmer** [comment]
@hdoupe said in PolicyBrain issue #830:
> I propose that we create a separate maintenance branch for pushing small features and bug fixes. As we phase in the changes for the CPS and benefits data, we will also need to quickly apply patches as bugs are discovered. One case where this would have been useful is yesterday in #836 where a separate branch with reverted changes had to be created in order to apply a minor patch.

Why do you need a separate branch?

If several commits have been made to the latest release and you find a bug in the release, simply create the bug-fixing branch from the release (not from the tip of the master branch).  I have done this several times over the past half year in my Tax-Calculator work.  Here are notes from my policybrain-builder "cheat-sheet":
```
CREATING NEW BRANCH TO FIX BUG
==============================

==> Fix bug, for example, in release 1.4.0 and then release 1.4.1

$ cd ~/work/OSPC/tax-calculator

$ git checkout master

$ git checkout  -b 1-4-1   1.4.0

... fix bug on branch 1-4-1, test, commit bug fix

$ git push upstream 1-4-1

... create release 1.4.1 using GitHub releases GUI citing branch 1-4-1

... then in order to merge bug-fix into master branch and future releases
    beginning with 1.5.0, do the following:

$ git checkout master

$ git merge 1-4-1
```

**Comment by hdoupe** [comment]
Ah, this sounds much easier. I was just about to start doing some `git` gymnastics to get this to work which would have surely caused a problem at some point. Thanks @martinholmer

**Comment by hdoupe** [comment]
Closing #839
