### ISSUE TITLE
Can PolicyBrain run under Python 3.6?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#845]
I'm asking because Pandas (and probably other libraries that Tax-Calculator uses) is going to stop supporting Python 2.7 at the end of 2018.  Would there be a problem if Tax-Calculator was available **only** as Python 3.6 packages beginning in 2019?

@MattHJensen @hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
@martinholmer Thanks for checking. I **cannot, cannot, cannot** wait for PolicyBrain to run on Python 3.6+. This will be one of our projects once we finish adding the CPS capabilities. So, no, this should not be a problem. I am confident that we will upgrade before 2019.

**Comment by martinholmer** [comment]
@hdoupe said:
> Thanks for checking. I cannot, cannot, cannot wait for PolicyBrain to run on Python 3.6+. This will be one of our projects once we finish adding the CPS capabilities. So, no, this should not be a problem. I am confident that we will upgrade before 2019.

Good to hear!

**Comment by martinholmer** [comment]
I have the answer to my question (thanks @hdoupe), so I'm going to close this issue.
