### ISSUE TITLE
"About a few seconds remaining" is awkward (extremely minor)

### ISSUE THREAD

**Issue by MaxGhenis** [OpenSourcePolicyCenter/PolicyBrain#850]
"A few seconds remaining" would be less awkward, but that would require more dynamic HTML: https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/6433ad630c020dad115802e4310e9fe22dd6ffc5/templates/taxbrain/not_ready.html#L17

An alternative could be:

    <h4>Estimated time remaining: <span id="eta"></span></h4>

**Comment by hdoupe** [comment]
@MaxGhenis thanks for the suggestion. This sounds sensible to me. Do you have the time/interest to put together a PR for this? I can guide you through the codebase if you have any questions.

**Comment by hdoupe** [comment]
Closed via #854
