### ISSUE TITLE
Macro Elasticity Simulation output page broken

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#855]
When TaxBrain users elect to do a "Macro Elasticity Simulation" they get this output page:

![screen shot 2018-03-21 at 7 54 50 am](https://user-images.githubusercontent.com/12170745/37708644-da7199a8-2cdd-11e8-9fd4-319739dc791b.png)

When picking any of the three "Save As" option, they get this:

![screen shot 2018-03-21 at 7 54 08 am](https://user-images.githubusercontent.com/12170745/37708699-0a070cfc-2cde-11e8-8a3e-17813cdc4754.png)

And when they click on Share and Print nothing happens.

**Comment by hdoupe** [comment]
@martinholmer thanks for the bug report!

**Comment by hdoupe** [comment]
Closed via #860
