### ISSUE TITLE
Render a special HTML page for when a model result is not found or is incompatible

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#869]
For cases where the result is not found or is incompatible with existing code, I think we should display a page with an explanation for what has happened and how the result could potentially be either reproduced or re-run on the newer model. The message would be something like:

"We are unable to display the results for model run #XXX. We apologize for the inconvenience and are working to provide a satisfactory solution for displaying and/or recovering results created using older versions of PolicyBrain. Here is one option for recreating your results:

Go to the following link: http://www.ospc.org/taxbrain/edit/XXX/?start_year={{fill_in_start_year}} and re-submit your parameters using the current version of PolicyBrain. Note that for older runs some parameters may have been deprecated. We recommend the upstream package documentation for alternative parameter choices.

The upstream package may have more options for re-creating results with the exact version of the package used in this run."

cc @MattHJensen @GoFroggyRun

**Comment by MattHJensen** [comment]
That sounds helpful to me. 

PolicyBrain users probably don't know what "upstream package" means.

**Comment by hdoupe** [comment]
What about "modeling software" or "modeling package" instead?

**Comment by GoFroggyRun** [comment]
We have a couple HTML formats that would fit the context. 

One extends TB's input resources:  
<img width="1254" alt="screen shot 2018-03-27 at 2 54 13 pm" src="https://user-images.githubusercontent.com/13324931/37988369-be94de3e-31ce-11e8-86b5-a5e0c65ac087.png">


The other would extend OSPC's home page:
<img width="1136" alt="screen shot 2018-03-27 at 2 52 44 pm" src="https://user-images.githubusercontent.com/13324931/37988371-bfb5030c-31ce-11e8-8a66-1321caaf94a2.png">

Layout-wise, I'm indifferent between the two. However, would it be more concise to use option II so that we could render the same page for dynamic/ccc/taxbrain (if applicable)?

**Comment by hdoupe** [comment]
I like the first option. I like the feel of still being "in" the TaxBrain app. However, I don't have a strong opinion on going one way or the other. If we go the second route, we need to be able to set the link to the edit parameters page and a link to the project repo.

@MattHJensen @andersonfrailey do you have any thoughts on which page we should display?

We need to display this type of page for CCC, too. We are unable to render some of the older runs right now (see #695).

**Comment by andersonfrailey** [comment]
Is this a TaxBrain specific issue or something that also comes up with Cost of Capitol? If it's just TaxBrain I also prefer the first option, otherwise I think the second would be better, unless we want to develop an individual webpage for each model.

**Comment by MattHJensen** [comment]
Technological and maintenance aside, I agree that staying in TB is a better user experience.

**Comment by MattHJensen** [comment]
I said:

> PolicyBrain users probably don't know what "upstream package" means.

@hdoupe said: 

> What about "modeling software" or "modeling package" instead?

Would it be onerous to say the model name here and provide a link to the modeling package? 

I'm not sure users will necessarily know which model to go and look at otherwise.

**Comment by hdoupe** [comment]
@MattHJensen said:
> Would it be onerous to say the model name here and provide a link to the modeling package's website?

That makes sense. We can do that.

I think we should create a separate page for TaxBrain and CCC. If we decide in the future that this is too much trouble, then we can revisit this problem. Does that seem sensible?

**Comment by MattHJensen** [comment]
That seems sensible.
