### ISSUE TITLE
Downloaded CSV files are not rectangular

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/PolicyBrain#885]
When importing a downloaded CSV file into a spreadsheet, it is so distorted it is useless.

The distortion is caused by fact that the first (title) line in the downloaded CSV file is not comma separated.  This is strange because the last (source) line is comma separated, as is the body of the table.

What's the schedule for fixing this serious bug?

@hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
@martinholmer Thanks for the bug report. I was able to open the CSV in Excel and Numbers (the Apple version of Excel). That being said, this is a CSV and not an Excel spreadsheet. Thus, the odd formatting is not helpful. I'm taking stock of the open issues today and will open an issue to outline PolicyBrain priorities for the near future.

**Comment by martinholmer** [comment]
@hdoupe said:
>  I was able to open the CSV in Excel and Numbers (the Apple version of Excel). That being said, this is a CSV and not an Excel spreadsheet. Thus, the odd formatting is not helpful. 

Yes, I too can open up the downloaded CSV files in my spreadsheet, but the non-rectangular format leaves the spreadsheet misaligned.

It's not just spreadsheets that will be processing downloaded CSV files.  And those other tools will be expecting a rectangular file.  That is, one that has the same number of comma-separated values per row.
The current TaxBrain CSV files are not like that.

**Comment by hdoupe** [comment]
Thanks @martinholmer. I agree. 

I haven't done anything with the CSV file code before. I'm having trouble figuring out where they are even created. @GoFroggyRun are the CSV files built with javascript?

**Comment by GoFroggyRun** [comment]
@hdoupe yes. These buttons are within the [`datatables.js`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/static/js/vendor/DataTables/datatables.js) file. And the function related to CSV output button can be found [here](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/static/js/vendor/DataTables/datatables.js#L27679).

**Comment by hdoupe** [comment]
@martinholmer #885 should have been fixed in PR #904. Are you interested in testing out this fix? You can verify it at https://ospc-test.herokuapp.com/

**Comment by martinholmer** [comment]
@hdoupe said:
> #885 should have been fixed in PR #904. Are you interested in testing out this fix? You can verify it at https://ospc-test.herokuapp.com/

Sorry, I don't have time.

**Comment by hdoupe** [comment]
Ok, closing #885.
