### ISSUE TITLE
Make tests fail when invalid variables are used inside templates

### ISSUE THREAD

**Issue by lucassz** [OpenSourcePolicyCenter/PolicyBrain#925]
By default, if a variable that isn't present in the context is used in a template, Django simply skips it, rather than raising an exception. This might not be good even in production, but I suggest that at least in testing we use [something like this snippet](https://djangosnippets.org/snippets/646/) to override this with strict checking, to catch misspellings, templates that use a variable that isn't accessible, etc. This could be done by creating a testing-specific `settings.py` file or some other method.

**Comment by hdoupe** [comment]
@lucassz is #925 relevant to #266?

**Comment by lucassz** [comment]
@hdoupe Yes, that's the same issue actually. Thanks for bringing that up.
